"""Pocket Hatchling's pieces as letter grids (one letter a pixel, '.' empty; letters in pal.SPRITE).
The pet is Pip: a lemon hatchling still wearing the bottom of its eggshell, a sprout on its head."""

SPROUTS = {
    "up": [".........kk.....", "......kk.kEgk...", ".....kEgkrgk...."],
    "perk": ["....kk...kkk....", "...kEgk.kEggk...", "....kggkrgkk...."],
    "wilt": ["................", ".....kkk.kkk....", "....kgggkrggk..."],
    "think": [".mm......kk.....", "m..m..kk.kEgk...", ".mm..kEgkrgk...."],
    "joy": ["..........kk....", ".....kkk.kEgk...", "....kEggkrgk...."],
}
TOP = [".....kkkrkk.....", "...kkvvvvvvkk..."]
CHIN = [".kvvvvvvvvvvvvk."]
SHELL = [
    ".kvvvkvvvkvvvkk.",
    "kPkvkPkvkPkvkPkk",
    "kPPkPPPkPPPkPPPk",
    "kPPPPPPPPPPPPPmk",
    ".kPPPPPPPPPPPmk.",
    "..kkkkkkkkkkkk..",
]

def pip(face, sprout="up", chin=CHIN, top=TOP):
    """Pip from its parts: 3 rows of sprout, 2 of head top, 4 of face, 1 chin, 6 of shell."""
    return SPROUTS[sprout] + top + face + chin + SHELL

FACES = {
    "idle":   ["..kvPPvvvvvvvk..", ".kvPvkvvvvkvvvk.", ".kvvvkvvvvkvvvk.", ".kvLLvvkkvvLLvk."],
    "blink":  ["..kvPPvvvvvvvk..", ".kvPvvvvvvvvvvk.", ".kvvkkvvvvkkvvk.", ".kvLLvvkkvvLLvk."],
    "listen": ["..kvPPvvvvvvvk..", ".kvPkPvvvvkPvvk.", ".kvvkkvvvvkkvvk.", ".kvLLvvkkvvLLvk."],
    "think":  ["..kvPPvvvvvvvk..", ".kvPvvkvvvvkvvk.", ".kvvvvvvvvvvvvk.", ".kvLLvvvkkvLLvk."],
    "happy":  ["..kvPPvvvvvvvk..", ".kvPvkvvvvkvvvk.", ".kvvkvkvvkvkvvk.", ".kvLLvkeekvLLvk."],
    "error":  ["..kvPPvvvvvvvk..", ".kvPvvvvvvvvvvk.", ".kvkkvvvvvvkkvk.", ".kvvvvkvkvviivk."],
}
def over(grid, piece, x0, y0):
    """Lay a little piece ('.' clear) on a grid at (x0, y0)."""
    rows = [list(r) for r in grid]
    for y, row in enumerate(piece):
        for x, ch in enumerate(row):
            if ch != ".":
                rows[y0 + y][x0 + x] = ch
    return ["".join(r) for r in rows]


NOTE = [".eee", ".e.e", ".e..", "ee..", "ee.."]
THOUGHT = [".kkkkk.", "kPkPkPk", ".kkkkk."]
HEART3 = ["e.e", "eee", ".e."]
_happy = pip(FACES["happy"], "joy", chin=[".kvvvvvkkvvvvvk."])
_happy = _happy[1:] + ["...mmmmmmmmmm..."]  # a hop: Pip up a row, its shadow on the ground
NOX = {
    "nox.idle": pip(FACES["idle"]),
    "nox.blink": pip(FACES["blink"]),
    "nox.listening": over(pip(FACES["listen"], "perk"), NOTE, 0, 0),
    "nox.thinking": over(pip(FACES["think"], "up"), THOUGHT, 0, 0),
    "nox.happy": over(over(_happy, HEART3, 0, 0), HEART3, 13, 1),
    "nox.error": pip(FACES["error"], "wilt", chin=[".kvvvvvkvkvivvk."]),
}

AVATARS = {
"avatar.moon": [
"....kkkkk.......",
"..kkvvvvvk......",
".kvPPvvvk.......",
".kvPvvvk.....k..",
"kvPvvvk.....kVk.",
"kvvvvk.......k..",
"kvvvvk..........",
"kvkkvk.......k..",
"kvvvvk......kVk.",
"kvLLvvk......k..",
"kvvvvvvk........",
".kvvvvvvk.....k.",
".kwvvvvvvkkkkkk.",
"..kwwvvvvvvvvwk.",
"...kkwwwwwwwkk..",
".....kkkkkkk....",
],
"avatar.bat": [
"................",
"................",
".....k....k.....",
"....kmk..kmk....",
"....kmmkkmmk....",
".kk.kmmmmmmk.kk.",
"knnkmPmmmmmmknnk",
"knnnkmkmmkmknnnk",
"knnnkmkmmkmknnnk",
"knnnkLmmmmLknnnk",
"knnnkmmkkmmknnnk",
"kknkkmmmmmmkknkk",
"k.kk.kmmmmk.kk.k",
"......kmmk......",
".......kk.......",
"................",
],
"avatar.raven": [
"................",
".....kkkkk......",
"....knnnnnk.....",
"...knmnnnnnk....",
"..knmnnnnnnnk...",
"..knnkPnnnnnnk..",
"..knnkknnnnnnk..",
"..knLLnnvvkkkkk.",
".knnnnnnkvvVVwk.",
".knnnnnnnkkkkk..",
"knnnnnnnnnnk....",
"knmnnnnnnnnnk...",
"knnmmnnnnnnnnk..",
".knnnmmnnnnnk...",
"..kkknnnnkkk....",
".....kkkkk......",
],
"avatar.rose": [
"......kkkk......",
"....kkLLLLkk....",
"...kLlkkkklLk...",
"..kLlkLLLLklLk..",
"..kLkLkkkkLkLk..",
"..kLkLkllkLkLk..",
"..kLlkLkkLklLk..",
"...kLlkkkklLk...",
"....kkLLLLkk....",
"..kk..kkkk..kk..",
".kgEk..kr..kEgk.",
".kggk..kr..kggk.",
"..kgrk.kr.krgk..",
"...kkrkkrkrkk...",
".....kkrrrk.....",
"......kkkk......",
],
"avatar.ghost": [
"......kkkk......",
"....kkPPPPkk....",
"...kPPPPPPPPk...",
"..kPPPPPPPPPPk..",
"..kPPCPPPPPPPk..",
".kPPPPPPPPPPPPk.",
".kPPkPPPPPkPPPk.",
".kPPkPPPPPkPPPk.",
".kPLLPPkkPPLLPk.",
".kPPPPPkpkPPPPk.",
".kPPPPPPkPPPPPk.",
".kPPPPPPPPPPPmk.",
".kPPPPPPPPPPmmk.",
".kPmPPmmPmPPmmk.",
".kkmkkmmkkmkkmk.",
"..k.k..kk..k.k..",
],
}

def sticker(motif):
    """A die-cut sticker, 16 × 16: the motif (≤ 12 × 12, its own outline) centred, a white border
    all round (8 neighbours, so the cut is rounded) and a plum outline outside that (4 neighbours)."""
    h, w = len(motif), max(map(len, motif))
    assert h <= 12 and w <= 12, (h, w)
    grid = [["."] * 16 for _ in range(16)]
    oy, ox = (16 - h) // 2, (16 - w) // 2
    for y, row in enumerate(motif):
        for x, ch in enumerate(row):
            if ch != ".":
                grid[oy + y][ox + x] = ch
    def ring(letter, near):
        add = []
        for y in range(16):
            for x in range(16):
                if grid[y][x] == "." and any(0 <= y + dy < 16 and 0 <= x + dx < 16 and grid[y + dy][x + dx] != "."
                                             for dx, dy in near):
                    add.append((y, x))
        for y, x in add:
            grid[y][x] = letter
    ring("P", [(dx, dy) for dx in (-1, 0, 1) for dy in (-1, 0, 1) if dx or dy])
    ring("k", [(1, 0), (-1, 0), (0, 1), (0, -1)])
    return ["".join(r) for r in grid]

MOTIFS = {
"dj": [  # a cassette: label, two reels, the head
"kkkkkkkkkkkk",
"kLLLLLLLLLLk",
"kLvvvvvvvvLk",
"kLkkkkkkkkLk",
"kLkPPkkPPkLk",
"kLkPPkkPPkLk",
"kLkkkkkkkkLk",
"kLLLLLLLLLLk",
"kLLkkkkkkLLk",
"kkkkkkkkkkkk",
],
"explorer": [  # a hot-air balloon
"...kkkkkk...",
"..kLPLvLLk..",
".kLPLvvLLLk.",
".kLLLvvLLLk.",
".kLLLvvLLlk.",
"..kLLvvLlk..",
"...kLvvlk...",
"....kkkk....",
"....k..k....",
"....kwwk....",
"....kVVk....",
"....kkkk....",
],
"night_owl": [  # a round owl under a moon
"..k......k..",
".kmk....kmk.",
".kmmkkkkmmk.",
"kmmmmmmmmmmk",
"kmPPkmmkPPkm",
"kmPkkmmkkPkm",
"kmPPkVVkPPkm",
"kmmmmkkmmmmk",
"kmmCmmmmCmmk",
".kmmCmmCmmk.",
"..kVkkkkVk..",
"...k....k...",
],
"early_bird": [  # the sun peeking over a cloud
"....kkkk....",
"..kkvvvvkk..",
".kvvvvvvvvk.",
"kvvkvvvvkvvk",
"kvvvvvvvvvvk",
"kvLvvkkvvLvk",
"kkkkPPkkPPkk",
"kPPPPPPPPPPk",
"kPPPPPPPPPmk",
".kkmPPPPmmk.",
"...kkkkkkk..",
],
"weekend": [  # an ice-cream cone
"....kkkk....",
"...kLPLLk...",
"..kLPLLLLk..",
"..kLLLeLLk..",
".kLLeLLLeLk.",
".kllllllllk.",
"..kVwVwVwk..",
"...kwVwVk...",
"...kVwVwk...",
"....kwVk....",
"....kVwk....",
".....kk.....",
],
"genre_guardian": [
"kkkkkkkkkkkk",
"kiiiiiiiiiik",
"kiPPiiiiiiik",
"kiPikkikkiik",
"kiiikLkLkiik",
"kiiikLLLkiik",
".kiiikLkiik.",
".kiiiikiiik.",
"..kiiiiiik..",
"...kiiiik...",
"....kkkk....",
"............",
],
"broken_record": [  # redrawn
"...kkkkkk...",
".kknnnnnnkk.",
".kmnnnnnkCk.",
"knmnnnnkCCCk",
"knnnkkkCCCkk",
"knnkeekCCknk",
"knnkeCCCknnk",
"knkCCCkknnnk",
"kkCCCknnnnnk",
".kCkknnnnnk.",
".kknnnnnnkk.",
"...kkkkkk...",
],
"marathon": [
"....kkkk....",
".....kk.....",
"...kkkkkk.k.",
"..kPPPPPPkk.",
".kPPPkPPPPk.",
".kPPPkPPPPk.",
".kPPPkkkPPk.",
".kPPPPPPPPk.",
".kPPPPPPPPk.",
"..kPPPPPPk..",
"...kkkkkk...",
"............",
],
"radio_host": [  # a little radio
".........k..",
"........k...",
".......k....",
"kkkkkkkkkkkk",
"kmmmmmmmmmmk",
"kmkkkkkmmmmk",
"kmkLkLkmkkmk",
"kmkkLkkmkPmk",
"kmkLkLkmkkmk",
"kmkkkkkmmmmk",
"kmmmmmmmmmmk",
"kkkkkkkkkkkk",
],
"task_hero": [
".....kk.....",
"....kvvk....",
"kk.kvvvvk.kk",
"kLkkvkvkvkLk",
"kLLkvvvvvkLk",
".kLLkvvvkLk.",
"..kLkvvvkLk.",
"..kLkvkvkLk.",
"..kkvkkkvkk.",
"...kvk.kvk..",
"...kk...kk..",
"............",
],
"grocery_runner": [  # a strawberry
"...kk..kk...",
"..kgEkkEgk..",
"...kgggrk...",
".kkkrggkkkk.",
"kpppkkkpppek",
"kpPpppppPpek",
"kppppPppppek",
".kpPpppppek.",
".kppppPppek.",
"..kpPppeek..",
"...kppeek...",
"....kkkk....",
],
"planner": [  # an alarm clock
".kk......kk.",
"kVVk....kVVk",
"kVkkkkkkkkVk",
".kkEPPPPEkk.",
".kEPPPPPPPEk",
"kEPPPPkPPPPE",
"kEPPPPkkkPPE",
"kEPPPPPPPPPE",
".kEPPPPPPPEk",
"..kkEEEEEkk.",
"..k.kkkkk.k.",
],
"wall_poet": [  # redrawn
"......kkkkk.",
".....kLLLLk.",
"....kLLLLk..",
"...kLLLLk...",
"..kLLLLk....",
".kvkkkk.....",
".kvvk.......",
"kPPk........",
"kPkk........",
"kkk.........",
],
"courier": [  # a letter with a heart seal
"kkkkkkkkkkkk",
"kPkPPPPPPPkk",
"kPPkPPPPPkPk",
"kPPPkPPPkPPk",
"kPPPPkkkPPPk",
"kPPPPkeekPPk",
"kPPPkeeeekPk",
"kPPkPkeekPPk",
"kPkPPPPkPPkk",
"kkkkkkkkkkkk",
],
"curator": [  # a crown
"k....k....k.",
"kk..kk...kk.",
"kVk.kVk.kVk.",
"kVVkVVVkVVk.",
"kVVVVVVVVVk.",
"kVeVVpVVeVk.",
"kwwwwwwwwwk.",
"kkkkkkkkkkk.",
],
"high_scorer": [  # a trophy
"kkkkkkkkkkkk",
"kVkvvvvvvkVk",
"kVkvPvvvvkVk",
"kVkvPvvvvkVk",
".kkvvvvvvkk.",
"..kVvvvvVk..",
"...kVVVVk...",
"....kVVk....",
"....kwwk....",
"..kkkkkkkk..",
"..kwwwwwwk..",
"..kkkkkkkk..",
],
"collector": [  # redrawn
"...kkkkkk...",
"..kiPiPimk..",
".kiPiiiPimk.",
"kkkkkkkkkkkk",
"kiPikiiikimk",
".kiikiikimk.",
"..kiikikmk..",
"...kiikmk...",
"....kimk....",
".....kk.....",
],
"game_hopper": [  # a frog mid-hop
"..kk...kk...",
".kPkk.kPkk..",
".kPkgkkPkgk.",
"kgkkgggkkgk.",
"kggggggggggk",
"kgLgkkkgLggk",
"kgggkeekgggk",
".kgggkkgggk.",
"kgkkggggkkgk",
"kk..kkkk..kk",
],
"console_hopper": [  # redrawn
"..kkkkkkkk..",
".kmmmmmmmmk.",
"kmmkkkkkkmmk",
"kmmkEEEEkmmk",
"kkmkEgEEkmek",
"kmkkEEEEkeek",
"kkmkkkkkkmek",
"kmmmmmmmmmmk",
".kmmkkkkmmk.",
"..kkk..kkk..",
],
"romhacker": [
"kkkkkkkkk...",
"kmmmmmmmk...",
"kmkkkkkmk...",
"kmkLLLkmk...",
"kmkLPLkmk.k.",
"kmkLLLkmkkVk",
"kmkkkkkmkVk.",
"kmmmmmmmVk..",
"kmkmkmkVk...",
"kkkkkkVkk...",
"....kVk.....",
"....kk......",
],
}
MEDALS = {"title." + name: sticker(m) for name, m in MOTIFS.items()}


ROOMS = {
"room.home": [
"................",
"..........kkk...",
"......kk..kVk...",
".....kLLk.kVk...",
"....kLLLLkkVk...",
"...kLPLLLLkkk...",
"..kLPLLLLLLLk...",
".kLLLLLLLLLLLk..",
"kkkkkkkkkkkkkkk.",
".kPPPPPPPPPPPk..",
".kPPePePPkkkPk..",
".kPPeeePPkLkPk..",
".kPPPePPPkLkPk..",
".kPPPPPPPkLkPk..",
".kkkkkkkkkkkkk..",
"................",
],
"room.listen": [
"................",
"......kkkkkkkk..",
"......kLLLLLLk..",
"......kLkkkkLk..",
"......kk....kk..",
"......k.....k...",
"......k.....k...",
"......k.....k...",
"...kkkk..kkkk...",
"..kLLLk.kLLLk...",
"..kLPLk.kLPLk...",
"..kLLLk.kLLLk...",
"...kkk...kkk....",
"................",
"................",
"................",
],
"room.watch": [
"................",
"....k.....k.....",
".....k...k......",
"......k.k.......",
"..kkkkkkkkkkkk..",
".kiiiiiiiiiiimk.",
".kikkkkkkkkkimk.",
".kikPPPPPPPPkmk.",
".kikPPPPLPPkkmk.",
".kikPPPPPPPPkmk.",
".kikkkkkkkkkkmk.",
".kiiiiiiiiiiimk.",
"..kkkkkkkkkkkk..",
"...kk......kk...",
"................",
"................",
],
"room.house": [
"................",
".....kkkkkk.....",
"....kkVVVVkk....",
"..kkkkkkkkkkkk..",
"..kPPPPPPPPPk...",
"..kPgkPPkkkPk...",
"..kPggPkPPPPk...",
"..kPkgkPPPPPPk..",
"..kPPPPPPPPPk...",
"..kPgkPPkkkPk...",
"..kPggPkPPPPk...",
"..kPkgkPPPPPPk..",
"..kPPPPPPPPPk...",
"..kkkkkkkkkkk...",
"................",
"................",
],
"room.files": [
"................",
"................",
"..kkkkk.........",
".kvvvvvk........",
".kvvvvvvkkkkkk..",
".kVVVVVVVVVVVVk.",
".kvvvvvvvvvvvvk.",
".kvvvvvvkvvvvvk.",
".kvvvvvvkkvvvvk.",
".kvvvvkkkkkvvvk.",
".kvvvvvkkkvvvvk.",
".kvvvvvkvkvvvvk.",
".kwwwwwwwwwwwwk.",
"..kkkkkkkkkkkk..",
"................",
"................",
],
"room.smart-home": [
"................",
"...k...k...k....",
"....k.kkk.k.....",
"......kvvvk.....",
".....kvvPvvk....",
"..k.kvvPvvvvk.k.",
".....kvvvvvvk...",
".....kvvvvvvk...",
"......kvvvvk....",
".......kkkk.....",
"......kmmmmk....",
"......kkkkkk....",
"......kmmmmk....",
".......kkkk.....",
"................",
"................",
],
"room.games": [
"................",
"................",
"...kkkk..kkkk...",
"..kmmmmkkmmmmk..",
".kmmmmmmmmmmmmk.",
".kmmkmmmmmmemmk.",
".kmkkkmmmmemmmk.",
".kmmkmmmmmmmmek.",
".kmmmmmkkmmmemk.",
".kmmmmkmmkmmmmk.",
"..kmmkk..kkmmk..",
"...kk......kk...",
"................",
"................",
"................",
"................",
],
"room.more": [
"................",
"................",
"..kkkkk.kkkkk...",
".kLLLLLkkEEEEEk.",
".kLPLLLkkEPEEEk.",
".kLLLLLkkEEEEEk.",
".kLLLLLkkEEEEEk.",
"..kkkkk.kkkkk...",
"..kkkkk.kkkkk...",
".kVVVVVkkmmmmmk.",
".kVPVVVkkmPmmmk.",
".kVVVVVkkmmmmmk.",
".kVVVVVkkmmmmmk.",
"..kkkkk.kkkkk...",
"................",
"................",
],
"room.me": [
"................",
".......kk.......",
"......kvvk......",
"......kvvk......",
".kkkkkvvvvkkkkk.",
".kvvvvvvvvvvvvk.",
"..kvvkvvvvkvvk..",
"...kvkvvvvkvk...",
"...kvLvkkvLvk...",
"...kvvvvvvvvk...",
"..kvvvvkkvvvvk..",
"..kvvvk..kvvvk..",
".kvvkk....kkvvk.",
".kkk........kkk.",
"................",
"................",
],
}
TRANSPORT = {
"transport.play": [
"kk.......",
"kPkk.....",
"kPPPkk...",
"kPPPPPkk.",
"kPPPPPPPk",
"kPPPPPkk.",
"kPPPkk...",
"kPkk.....",
"kk.......",
],
"transport.pause": [
"kkkk.kkkk",
"kPPk.kPPk",
"kPPk.kPPk",
"kPPk.kPPk",
"kPPk.kPPk",
"kPPk.kPPk",
"kPPk.kPPk",
"kPPk.kPPk",
"kkkk.kkkk",
],
"transport.stop": [
".........",
".kkkkkkk.",
".kPPkkkk.",
".kPkkkkk.",
".kkkkkkk.",
".kkkkkkk.",
".kkkkkkk.",
".kkkkkkk.",
".........",
],
"transport.next": [
".........",
"k...k...k",
"kk..kk..k",
"kPk.kPk.k",
"kkkkkkkkk",
"kkk.kkk.k",
"kk..kk..k",
"k...k...k",
".........",
],
"transport.previous": [
".........",
"k...k...k",
"k..kk..kk",
"k.kPk.kPk",
"kkkkkkkkk",
"k.kkk.kkk",
"k..kk..kk",
"k...k...k",
".........",
],
}
ALL = {**NOX, **AVATARS, **MEDALS, **ROOMS, **TRANSPORT}
