"""Pocket Hatchling's tokens, written from the palette (python3 tokens_src.py → tokens.json).
Only what differs from Base. Colours are pal.py's; the reasons are in BRIEF.md."""
from pal import *
from util import THEME, write_json

def a(colour, pct):
    return f"alpha({colour}, {pct}%)"

C = {  # color.*
    "bg.canvas": "#efe8fd", "bg.surface": "#fffaf4", "bg.raised": WHITE, "bg.overlay": "#fffaf4",
    "bg.sunken": WHITE, "bg.hover": P4, "bg.pressed": P3, "bg.selected": P3,
    "bg.inverse": INK,
    "fg.default": INK, "fg.muted": INK2, "fg.subtle": "#553869", "fg.placeholder": "#553869",
    "fg.disabled": "#a996b6", "fg.inverse": "#fff4fa", "fg.link": "#a3124f",
    "border.subtle": "#e6d3ec", "border.default": "#c3a3d2", "border.strong": INK3,
    "focus-ring": BERRY,
    "accent.solid": BERRY, "accent.solid-hover": BERRY_DEEP, "accent.soft": P4, "accent.fg": "#a3124f",
    "accent.border": P1,
    "success.solid": "#23806b", "success.soft": MINT3, "success.fg": "#1b6b58", "success.border": MINT1,
    "warning.solid": "#b07c00", "warning.soft": LEM3, "warning.fg": "#8a5200", "warning.border": LEM1,
    "danger.solid": "#c42e2e", "danger.soft": "#ffe3dc", "danger.fg": "#b02e17", "danger.border": CORAL,
    "info.solid": BLU0, "info.soft": BLU3, "info.fg": "#2f62a3", "info.border": BLU1,
    "private.solid": LAV0, "private.soft": LAV3, "private.fg": "#5a47a0",
    "paper.bg": LEM3, "paper.fg": INK, "paper.muted": INK2,
    "shadow": INK, "scrim": a(INK, 42), "media-scrim": a(INK, 64),
}
ROOMS = {
    "home": "oklch(0.52 0.16 355)", "listen": "oklch(0.5 0.17 12)", "watch": "oklch(0.5 0.13 250)",
    "games": "oklch(0.5 0.1 172)", "house": "oklch(0.53 0.12 72)", "files": "oklch(0.54 0.14 45)",
    "ask": "oklch(0.5 0.15 295)", "me": "oklch(0.52 0.16 335)", "control": "oklch(0.48 0.06 280)",
    "smart-home": "oklch(0.52 0.11 105)", "inbox": "oklch(0.5 0.11 225)", "space": "oklch(0.49 0.14 310)",
    "party": "oklch(0.55 0.17 28)",
}
PEOPLE = ["#cc3f7c", "#c95a22", "#9a6f00", "#23806b", "#227f9e", "#3c6fb2", "#6653ad", "#9d45a3"]
DATA = ["#cc3f7c", "#23806b", "#6653ad", "#9a6f00", "#3c6fb2", "#c95a22", "#9d45a3", "#227f9e"]

def text(family, size, weight, lh, ls=None):
    v = {"fontFamily": "{font.%s}" % family, "fontSize": size, "fontWeight": weight, "lineHeight": lh}
    if ls is not None:
        v["letterSpacing"] = ls
    return {"$value": v}

GLOSS = "radial-gradient(circle at 11px 9px, #ffffffd9 0 2.5px, transparent 3.5px)"

def tokens():
    color = {"$type": "color"}
    for key, value in C.items():
        node = color
        *path, last = key.split(".")
        for p in path:
            node = node.setdefault(p, {})
        node[last] = {"$value": value}
    color["room"] = {k: {"$value": v} for k, v in ROOMS.items()}
    color["person"] = {str(i + 1): {"$value": v} for i, v in enumerate(PEOPLE)}
    color["data"] = {str(i + 1): {"$value": v} for i, v in enumerate(DATA)}
    color["sprite"] = {name: {"$value": hexv} for name, hexv in SPRITE.values()}
    s = lambda v: {"$type": "string", "$value": v}
    col = lambda v: {"$type": "color", "$value": v}
    sh = lambda v: {"$type": "shadow", "$value": v}
    dim = lambda v: {"$type": "dimension", "$value": v}
    ink_edge = f"1px solid {INK}"
    return {
        "$schema": "../_schema/tokens.schema.json",
        "$description": "Pocket Hatchling: a keychain pet living on a handmade homepage. Candy plastic, plum ink outlines, a reflective LCD, one berry button. Generated by docs/design/themes/pocket-hatchling/tokens_src.py.",
        "seed": {"$type": "color",
                 "neutral": {"$value": "oklch(0.55 0.05 318)"}, "accent": {"$value": "oklch(0.52 0.19 358)"},
                 "success": {"$value": "oklch(0.55 0.1 172)"}, "warning": {"$value": "oklch(0.6 0.13 70)"},
                 "danger": {"$value": "oklch(0.56 0.18 33)"}, "info": {"$value": "oklch(0.55 0.12 250)"},
                 "private": {"$value": "oklch(0.52 0.15 290)"}},
        "color": color,
        "font": {"$type": "fontFamily", "display": {"$value": ["DynaPuff", "system-ui", "sans-serif"]},
                 "body": {"$value": ["Nunito", "system-ui", "sans-serif"]},
                 "mono": {"$value": ["Pixelify Sans", "ui-monospace", "monospace"]}},
        "text": {"$type": "typography",
                 "display-xl": text("display", 47, 600, 1.1, 0), "display-l": text("display", 36, 600, 1.12, 0),
                 "display-m": text("display", 29, 600, 1.15, 0), "brand": text("display", 20, 600, 1.2, 0),
                 "title-l": text("body", 23, 800, 1.2), "title-m": text("body", 19, 800, 1.25),
                 "title-s": text("body", 17, 800, 1.25),
                 "body-l": text("body", 18, 500 if False else 400, 1.5), "body-m": text("body", 16, 400, 1.5),
                 "body-s": text("body", 14, 600, 1.45), "action": text("body", 15, 800, 1.2, 0.01),
                 "label": text("body", 13, 800, 1.2, 0.02), "caption": text("body", 12, 600, 1.35, 0),
                 "numeric": text("mono", 15, 400, 1.12)},
        "radius": {"$type": "dimension", "xs": {"$value": 4}, "s": {"$value": 8}, "m": {"$value": 14},
                   "l": {"$value": 18}, "xl": {"$value": 24},
                   "control": {"$value": "{radius.m}"}, "card": {"$value": 10},
                   "sheet": {"$value": "{radius.xl}"}, "chip": {"$value": "{radius.full}"},
                   "media": {"$value": "{radius.s}"}, "avatar": {"$value": "{radius.full}"}},
        "elev": {"$type": "shadow",
                 "1": {"$value": f"0 2px 0 {a(INK, 16)}"},
                 "2": {"$value": f"0 3px 0 {a(INK, 18)}"},
                 "3": {"$value": f"0 4px 0 {a(INK, 20)}, 0 10px 22px {a(INK, 12)}"},
                 "4": {"$value": f"0 6px 0 {a(INK, 18)}, 0 18px 44px {a(INK, 22)}"}},
        "material": {
            "surface": {"border": s(ink_edge), "shadow": sh(f"3px 4px 0 {a(INK, 14)}"),
                        "radius": dim("{radius.card}")},
            "raised": {"bg": col(WHITE), "border": s(ink_edge), "shadow": sh(f"0 2px 0 {INK}")},
            "overlay": {"border": s(ink_edge), "shadow": sh("{elev.4}")},
            "sunken": {"border": s(f"1px solid {INK3}"), "shadow": sh(f"inset 0 2px 0 {a(INK, 7)}")},
            "inverse": {"bg": col(INK), "fg": col("#fff4fa")},
            "paper": {"bg": col(LEM3), "fg": col(INK), "rotate": s("1.4deg"),
                      "shadow": sh(f"3px 4px 0 {a(INK, 14)}")},
            "media": {"border": s(ink_edge), "shadow": sh(f"2px 3px 0 {a(INK, 14)}")},
            "screen": {"bg": col(LCD3), "fg": col(LCD0), "texture": s("url(art/lcd.svg)"),
                       "glow": sh(f"inset 2px 2px 0 {a(LCD0, 18)}")},
        },
        "part": {
            "page": {"scrim": col(a("#efe8fd", 40)), "gallery": col(P4)},
            "status": {"bg": col(P2), "border": s(ink_edge), "art-opacity": s("1")},
            "rail": {"bg": col(MINT3), "border": s(f"1px dashed {INK}"), "texture": s("url(art/dots.svg)")},
            "dock": {"bg": col(P3), "border": s(ink_edge), "texture": s("url(art/glitter.svg)")},
            "nowbar": {"bg": col(LCD3), "fg": col(LCD0), "border": s(ink_edge), "radius": dim("{radius.l}"),
                       "texture": s("url(art/lcd.svg)"),
                       "shadow": sh(f"0 0 0 4px {P2}, 0 0 0 5px {INK}, 0 7px 0 5px {a(INK, 16)}")},
            "header": {"fg": col(INK), "kicker": col(INK2), "banner-wash": {"$type": "number", "$value": 0}},
            "panel": {"head": col("#a8316e")},
            "sheet": {"texture": s("url(art/glitter.svg)")},
            "control": {"bg": s(f"{GLOSS}, linear-gradient({WHITE} 0 50%, #fff0f7 50% 100%)"),
                        "shadow": sh(f"0 2px 0 {INK}"),
                        "primary-bg": s(f"{GLOSS}, {BERRY}"),
                        "primary-shadow": sh(f"0 2px 0 {INK}, inset 0 -3px 0 {a(BERRY_DEEP, 70)}")},
            "meter": {"track": col(LAV3), "thumb": col(INK),
                      "pattern": s(f"repeating-linear-gradient(135deg, {a(WHITE, 42)} 0 4px, transparent 4px 8px)")},
        },
        "dur": {"$type": "duration", "fast": {"$value": 110}, "base": {"$value": 170},
                "slow": {"$value": 260}, "slower": {"$value": 380}},
        "ease": {"$type": "cubicBezier", "standard": {"$value": [0.25, 0.1, 0.25, 1]},
                 "enter": {"$value": [0.34, 1.56, 0.64, 1]}, "exit": {"$value": [0.5, 0, 0.75, 0]},
                 "emphasized": {"$value": [0.45, 1.8, 0.4, 1]}},
        "icon": {"stroke": {"$type": "number", "$value": 2}},
    }

if __name__ == "__main__":
    write_json(THEME / "tokens.json", tokens())
    print("tokens.json written")
