"""The house's little drawings, as letter grids (themes/_schema/sprites.ids.json): Nox the
station cat, the five avatars, the room marks, the transport keys, the twenty medals.

Letters → color.sprite tokens (tokens.json paints them; the same colours as px.PAL):
  k outline (navy ink)   n dark (navy enamel)  c light (navy blue)   L mid (steel blue)
  l mid-dark (steel)     m mist (sky)          P paper (cream white) C light-dim (tan)
  e accent (signal red)  E accent-hi           r accent-deep         p alert (sunflower yellow)
  v familiar (ginger)    V familiar-mid        w familiar-deep       g good (green)
  i ink (wood)
Light from the upper left, like every picture of the theme."""

PALETTE = {
    "k": "outline", "n": "dark", "c": "light", "L": "mid", "l": "mid-dark", "m": "mist",
    "P": "paper", "C": "light-dim", "e": "accent", "E": "accent-hi", "r": "accent-deep",
    "p": "alert", "v": "familiar", "V": "familiar-mid", "w": "familiar-deep", "g": "good", "i": "ink",
}

# ------------------------------------------------------------------ Nox, the station cat
# Row 0 carries the mood's sign (a note, thought dots); the ears, eyes and mouth do the rest.
_CAP = [
    ".kvVkknnnnnkVvk.",
    ".kvvknnnnpnkvvk.",
    ".kvkkkkkkkkkkvk.",
]
_BODY = [
    "..kVvvvvvvvvVkkk",
    ".kVvPPPPPPPPvVkv",
    "..kkkkkkkkkkkkk.",
]
_EARS = [".kk..........kk.", "kVk..kkkkkk..kVk"]


def _nox(sign, ears, face):
    return [sign] + ears + _CAP + face + _BODY


NOX = {
    "nox.idle": _nox("................", _EARS, [
        "kvvvvvvvvvvvvvvk",
        "kvvkkvvvvvvkkvvk",
        "kvvkPvvvvvvkPvvk",
        "kVvvvvPPPPvvvvVk",
        ".kvvvPPePPPvvvk.",
        "..kkwPPPPPPwkk..",
    ]),
    "nox.blink": _nox("................", _EARS, [
        "kvvvvvvvvvvvvvvk",
        "kvvvvvvvvvvvvvvk",
        "kvkkkvvvvvvkkkvk",
        "kVvvvvPPPPvvvvVk",
        ".kvvvPPePPPvvvk.",
        "..kkwPPPPPPwkk..",
    ]),
    "nox.listening": _nox(".k.....mm.....k.", ["kVk...mm.....kVk", "kVk..kkkkkk..kVk"], [
        "kvvvvvvvvvvvvvvk",
        "kvvkkvvvvvvkkvvk",
        "kvvkkvvvvvvkkvvk",
        "kVvvvvPPPPvvvvVk",
        ".kvvvPPePPPvvvk.",
        "..kkwPPkkPPwkk..",
    ]),
    "nox.thinking": _nox("..........c.c.c.", _EARS, [
        "kvvvvvvvvvvvvvvk",
        "kvvvkPvvvvvvkPvk",
        "kvvvkkvvvvvvkkvk",
        "kVvvvvPPPPvvvvVk",
        ".kvvvPPePPPvvvk.",
        "..kkwPPPkkkwkk..",
    ]),
    "nox.happy": _nox("................", _EARS, [
        "kvvvvvvvvvvvvvvk",
        "kvvvkvvvvvvkvvvk",
        "kvvkvkvvvvkvkvvk",
        "kVEvvvPPPPvvvEVk",
        ".kvvvPkeekPvvvk.",
        "..kkwPkrrkPwkk..",
    ]),
    "nox.error": _nox("..............m.", [".kk..........km.", "kVk..kkkkkk..kmk"], [
        "kvvvvvvvvvvvvvvk",
        "kvkvkvvvvvvkvkvk",
        "kvvkvvvvvvvvkvvk",
        "kVkvkvPPPPvkvkVk",
        ".kvvvPPePPPvvvk.",
        "..kkwPkkkkPwkk..",
    ]),
}

# ------------------------------------------------------------------ avatars (fill the ring)
AVATARS = {
    "avatar.moon": [  # a summer night: crescent moon and a star over the far hills
        ".....kkkkkk.....",
        "...kknnnnnnkk...",
        "..knnnnnnnnnnk..",
        ".knnnnnnppnnnnk.",
        ".knnnnnpVnnnnnk.",
        "knnPnnpVnnnnnnnk",
        "knnnnnpVnnnnnnnk",
        "knnnnnpVnnnnnnnk",
        "knnnnnnpVnnnnPnk",
        "knnnnnnnppnnnnnk",
        "knnnnnnnnnnnnnnk",
        ".kLLnnnnnnnnLLk.",
        ".kgLLLLnnLLLLgk.",
        "..kggggLLggggk..",
        "...kkggggggkk...",
        ".....kkkkkk.....",
    ],
    "avatar.bat": [  # a bat crossing the rising moon at dusk
        ".....rrrrrr.....",
        "...rrEEEEEErr...",
        "..rEEEEppEEEEr..",
        ".rEEEppppppEEEr.",
        ".rEEppppppppEEr.",
        "rEEEpkpppkppEEEr",
        "rEEEpkkkkkppEEEr",
        "rkEEpkPkPkppEEkr",
        "rkkEEpkkkkpEEkkr",
        "rkkkkkkkkkkkkkkr",
        "rEkkkkkkkkkkkkEr",
        ".rEkkEkkkkEkkEr.",
        ".rEEEEEkkEEEEEr.",
        "..rEEEEEEEEEEr..",
        "...rrEEEEEErr...",
        ".....rrrrrr.....",
    ],
    "avatar.raven": [  # a crow on the catenary wire
        ".....kkkkkk.....",
        "...kkmmmmmmkk...",
        "..kmmmmmmmmmmk..",
        ".kmmmmmkkkmmmmk.",
        ".kmmmmkkkPkmmmk.",
        "kmmmmmkkkkkCCmmk",
        "kmmmmkkkkkkmmmmk",
        "kmmmkkkkkkkmmmmk",
        "kmmkkkkkkkkmmmmk",
        "kmkkkkkkkkkmmmmk",
        "kmmmmmkCmkCmmmmk",
        "nnnnnnnnnnnnnnnn",
        ".kmmmmmmmmmmmmk.",
        "..kmmmmmmmmmmk..",
        "...kkmmmmmmkk...",
        ".....kkkkkk.....",
    ],
    "avatar.rose": [  # a red rose from the stationmaster's garden
        ".....kkkkkk.....",
        "...kkPPPPPPkk...",
        "..kPPPPkkkkPPk..",
        ".kPPPkkEeeekkPk.",
        ".kPPkEEeeEeerkk.",
        "kPPPkEeEEreErkPk",
        "kPPPkeeeEeerrkPk",
        "kPPPkreeeerrrkPk",
        "kPPPPkrrrrrrkPPk",
        "kPPPPPkkkkgkPPPk",
        "kPPgggPPPkgkPPPk",
        ".kPPgggPPgkPPPk.",
        ".kPPPPggggPPPPk.",
        "..kPPPPPgPPPPk..",
        "...kkPPPgPPkk...",
        ".....kkkkkk.....",
    ],
    "avatar.ghost": [  # the lantern ghost of summer stories: one eye, a long tongue
        ".....kkkkkk.....",
        "...kknnnnnnkk...",
        "..knnnkkkknnnk..",
        ".knnnkPPPPknnnk.",
        ".knnkPCPPPPknnk.",
        "knnkPPPPPPPPknnk",
        "knnkCCCCCCCCknnk",
        "knnkPPkkkPPPknnk",
        "knnkPkPPkkPPknnk",
        "knnkCCkkkCCCknnk",
        "knnkPPPPeePPknnk",
        ".knnkPPPeePknnk.",
        ".knnnkkkEekknnk.",
        "..knnnnnkeknnk..",
        "...kknnnnnnkk...",
        ".....kkkkkk.....",
    ],
}

# ------------------------------------------------------------------ room marks
ROOMS = {
    "room.home": [  # the little station house: red roof, cream walls, a clock
        "................",
        "......kkkk......",
        ".....kEEEEk.....",
        "...kkEeeeeEkk...",
        "..kEeeeeeeeeek..",
        ".kEeeeeeeeeeeek.",
        "kkkkkkkkkkkkkkkk",
        ".kPPPPPkkPPPPPk.",
        ".kPPPPkPPkPPPPk.",
        ".kPCCPkPkkPCCPk.",
        ".kPCCPPkkPPCCPk.",
        ".kPPPPPPPPPPPPk.",
        ".kPPkkkPPkkkPPk.",
        ".kCCkiiCCkiiCCk.",
        ".kCCkiiCCkiiCCk.",
        "kkkkkkkkkkkkkkkk",
    ],
    "room.listen": [  # the table radio
        "................",
        "............k...",
        "...........k....",
        "..kkkkkkkkkkkk..",
        ".kiiiiiiiiiiiik.",
        ".kiCCCCCCCiPPik.",
        ".kiCkCkCkCiPePik",
        ".kiCCCCCCCiPPik.",
        ".kiCkCkCkCiiiik.",
        ".kiCCCCCCCikkik.",
        ".kiCkCkCkCikpik.",
        ".kiCCCCCCCikkik.",
        ".kiiiiiiiiiiiik.",
        "..kkkkkkkkkkkk..",
        "..kk........kk..",
        "................",
    ],
    "room.watch": [  # the waiting-room television on its legs
        "..k........k....",
        "...k......k.....",
        "....k....k......",
        ".....kkkk.......",
        ".kkkkkkkkkkkkkk.",
        ".kiiiiiiiiiiiik.",
        ".kikkkkkkkkiiik.",
        ".kikmmmmmmkiPik.",
        ".kikmPmmmmkiiik.",
        ".kikmmmmmmkiPik.",
        ".kikLLLLLLkiiik.",
        ".kikkkkkkkkiiik.",
        ".kiiiiiiiiiiiik.",
        ".kkkkkkkkkkkkkk.",
        "..kk........kk..",
        ".kk..........kk.",
    ],
    "room.games": [  # a spinning top
        ".......kk.......",
        ".......kk.......",
        "......kiik......",
        "....kkkkkkkk....",
        "...kpppppppppk..",
        "..kPpppppppppek.",
        ".kPpeeeeeeeeeeek",
        ".kpeeeeeeeeeeerk",
        ".kccccccccccccck",
        "..kcccccccccccnk",
        "...kPPPPPPPPPk..",
        "....kCCCCCCCk...",
        ".....kCCCCCk....",
        "......kCCk......",
        ".......kk.......",
        "................",
    ],
    "room.house": [  # the station's notice board, today's notes pinned on it
        "................",
        ".kkkkkkkkkkkkkk.",
        ".kiiiiiiiiiiiik.",
        ".kiPPPPPiPPPPik.",
        ".kiPePPPiPpPPik.",
        ".kiPkkkPiPPPPik.",
        ".kiPPPPPiPkkPik.",
        ".kiPkkPPiPPPPik.",
        ".kiPPPPPiiiiiik.",
        ".kiiiiiiiPPPPik.",
        ".kiPPPPPiPgPPik.",
        ".kiPkkkPiPkkPik.",
        ".kiPPPPPiPPPPik.",
        ".kiiiiiiiiiiiik.",
        ".kkkkkkkkkkkkkk.",
        "...kk......kk...",
    ],
    "room.files": [  # the parcels office's trunk, strapped
        "................",
        "................",
        "......kkkk......",
        ".....kk..kk.....",
        ".kkkkkkkkkkkkkk.",
        "kwvvkvvvvvvkvvwk",
        "kvVVkVVVVVVkVVvk",
        "kvvvkvvvvvvkvvvk",
        "kkkkkkkppkkkkkkk",
        "kvvvkvvkkvvkvvvk",
        "kvvvkvvvvvvkvvvk",
        "kvvvkvvvvvvkvvvk",
        "kwwwkwwwwwwkwwwk",
        ".kkkkkkkkkkkkkk.",
        "..kk........kk..",
        "................",
    ],
    "room.smart-home": [  # the colour-light signal, green: all clear
        "....kkkkkkk.....",
        "...kkkkkkkkk....",
        "...kkkgggkkk....",
        "...kkgPggkkk....",
        "...kkkgggkkk....",
        "...kkkkkkkkk....",
        "...kkknnnkkk....",
        "...kkknknkkk....",
        "...kkknnnkkk....",
        "....kkkkkkk.....",
        "......klk.......",
        "......klk.......",
        "......klk.......",
        "......klk.......",
        "....kkkkkkk.....",
        "...kCCCCCCCk....",
    ],
    "room.me": [  # the stationmaster's cap
        "................",
        "................",
        "....kkkkkkkk....",
        "..kknnnnnnnnkk..",
        ".knnnnnnnnnnnnk.",
        "kncnnnnkpknnnnnk",
        "kncnnnkpppknnnnk",
        "knnnnnnkpknnnnnk",
        "kkkkkkkkkkkkkkkk",
        "keeeeeeeeeeeeeek",
        "kEEEEEEEEEEEEEEk",
        ".kkkkkkkkkkkkkk.",
        "..kkkkkkkkkkkk..",
        "...kkkkkkkkkk...",
        "................",
        "................",
    ],
    "room.more": [  # the ticket rack's pigeonholes
        "................",
        ".kkkkkkkkkkkkkk.",
        ".kiiiiiiiiiiiik.",
        ".kikPPkikmmkiik.",
        ".kikPPkikmmkiik.",
        ".kikPPkikmmkiik.",
        ".kiiiiiiiiiiiik.",
        ".kikEEkikppkiik.",
        ".kikEEkikppkiik.",
        ".kikEEkikppkiik.",
        ".kiiiiiiiiiiiik.",
        ".kikggkikCCkiik.",
        ".kikggkikCCkiik.",
        ".kiiiiiiiiiiiik.",
        ".kkkkkkkkkkkkkk.",
        "................",
    ],
}

# ------------------------------------------------------------------ transport keys (enamel pictograms)
TRANSPORT = {
    "transport.play": ["kk.......", "kPkk.....", "kPPPkk...", "kPPPPPkk.", "kPPPPPPPk", "kPPPPPkk.", "kPPPkk...", "kPkk.....", "kk......."],
    "transport.pause": ["kkkk.kkkk", "kPPk.kPPk", "kPPk.kPPk", "kPPk.kPPk", "kPPk.kPPk", "kPPk.kPPk", "kPPk.kPPk", "kPPk.kPPk", "kkkk.kkkk"],
    "transport.next": ["kk....kkk", "kPk...kPk", "kPPk..kPk", "kPPPk.kPk", "kPPPPkkPk", "kPPPk.kPk", "kPPk..kPk", "kPk...kPk", "kk....kkk"],
    "transport.previous": ["kkk....kk", "kPk...kPk", "kPk..kPPk", "kPk.kPPPk", "kPkkPPPPk", "kPk.kPPPk", "kPk..kPPk", "kPk...kPk", "kkk....kk"],
    "transport.stop": ["kkkkkkkkk", "kPPPPPPPk", "kPPPPPPPk", "kPPPPPPPk", "kPPPPPPPk", "kPPPPPPPk", "kPPPPPPPk", "kPPPPPPPk", "kkkkkkkkk"],
}

# ------------------------------------------------------------------ the twenty medals: station objects
MEDALS = {
    "title.dj": [  # the platform's horn loudspeaker, calling out
        "................",
        "..........kk....",
        ".........kPck...",
        "........kPcck.m.",
        ".......kPccck..m",
        "..kkkkkPcccck.m.",
        ".kLLLLkPccccck..",
        ".kLllLkccccnck.m",
        ".kLLLLkPccccck..",
        "..kkkkkPcccck.m.",
        "....kl.kPccck..m",
        "....kl..kPcck.m.",
        "....kl...kPck...",
        "....kl....kk....",
        "..kkkkkk........",
        "..kCCCCk........",
    ],
    "title.explorer": [  # the signpost at the crossroads, arrows only
        ".......kk.......",
        ".kkkkkkkkkkkkk..",
        "kPPPPPPPPPPPPPk.",
        "kPcccccccccPPPPk",
        "kPPPPPPPPPPPPPk.",
        ".kkkkkkkkkkkkk..",
        "..kkkkkkkkkkkkk.",
        ".kEEEEEEEEEEEEEk",
        "kEEPPPPPPPPPEEEk",
        ".kEEEEEEEEEEEEEk",
        "..kkkkkkkkkkkkk.",
        ".......ki.......",
        ".......ki.......",
        ".......ki.......",
        ".....gkkikg.....",
        "...ggggggggggg..",
    ],
    "title.night_owl": [  # the hand lamp of the last train
        "......kkkk......",
        ".....k....k.....",
        "......kkkk......",
        "....kkllllkk....",
        "...klPPPPPPlk...",
        "...klpppppplk...",
        "..kkkkkkkkkkkk..",
        "..klPPpPPPPplk..",
        "..klPpppppppk...",
        "..klpppEEpplk...",
        "..klppEEEEplk...",
        "..klppEeeEplk...",
        "..klpppeeepplk..",
        "..kkkkkkkkkkkk..",
        "...klllllllk....",
        "....kkkkkkkk....",
    ],
    "title.early_bird": [  # the first sun over the rails
        "................",
        "......k..k......",
        "..k....pp....k..",
        "...k.pppppp.k...",
        "....pppEEppp....",
        "...ppEEEEEEpp...",
        "k.ppEEEEEEEEpp.k",
        "..pEEEEEEEEEEp..",
        "mmmmmmmmmmmmmmmm",
        "mmmmmmkmmkmmmmmm",
        "LLLLLkLLLLkLLLLL",
        "iiiikiiiiiikiiii",
        "LLLkLLLLLLLLkLLL",
        "iikiiiiiiiiiikii",
        "LkLLLLLLLLLLLLkL",
        "kiiiiiiiiiiiiiik",
    ],
    "title.weekend": [  # a bottle of ramune, its marble in the neck
        "......kkkk......",
        "......kEEk......",
        "......kkkk......",
        ".....kmPmmk.....",
        ".....kmmmmk.....",
        "....kmmkkmmk....",
        "....kmkPPkmk....",
        "....kmkPmkmk....",
        "...kmmmkkmmmk...",
        "...kPmmmmmmmmk..",
        "...kPmnnnnnmmk..",
        "...kPmnPPPnmmk..",
        "...kPmnnnnnmmk..",
        "...kPmmmmmmmmk..",
        "...kmmmmmmmmmk..",
        "....kkkkkkkkk...",
    ],
    "title.genre_guardian": [  # the semaphore signal standing guard over the line
        "...........kk...",
        "..........kPk...",
        "..kkkkkkkkkkk...",
        ".kEEEPPPEEEkk...",
        ".kEEEPPPEEEkPk..",
        "..kkkkkkkkkk....",
        "...........kk...",
        "..........kgk...",
        "..........kek...",
        "...........kk...",
        "...........lk...",
        "...........lk...",
        "...........lk...",
        "...........lk...",
        ".........kkkkk..",
        "........kCCCCCk.",
    ],
    "title.broken_record": [  # a round-trip card ticket, clipped
        "................",
        "................",
        ".kkkkkkkkkkkkkk.",
        ".kVVVVVVVVVVVVk.",
        ".kVkkkkkkkkkkVk.",
        "..VkVVVVVVVVkVk.",
        "..VkVcccccVVkVk.",
        ".kVkVVVVVVVVkVk.",
        ".kVkVcccVeVVkVk.",
        ".kVkVVVVeeeVkVk.",
        ".kVkVcccVeVVkVk.",
        ".kVkVVVVVVVVk.k.",
        ".kVkkkkkkkkkk.k.",
        ".kVVVVVVVVVVVVk.",
        ".kkkkkkkkkkkkkk.",
        "................",
    ],
    "title.marathon": [  # the long-haul express's nose, headlamp lit
        "................",
        "....kkkkkkkk....",
        "...kPPPPPPPPk...",
        "..kPPPPpPPPPPk..",
        ".kPmmmmkkmmmmPk.",
        ".kPmPmmkkmPmmPk.",
        ".kPmmmmkkmmmmPk.",
        ".kPPPPPPPPPPPPk.",
        ".keeeeeeeeeeeek.",
        ".kEEEEEEEEEEEEk.",
        ".kePpeeeeeepPek.",
        ".keeeeeeeeeeeek.",
        ".krrrrkkkkrrrrk.",
        "..kkkkllllkkkk..",
        "...lk.kkkk.kl...",
        "..kkkkkkkkkkkk..",
    ],
    "title.radio_host": [  # the station master's valve radio, dial glowing
        "......k..k......",
        ".......kk.......",
        ".kkkkkkkkkkkkkk.",
        "kiiiiiiiiiiiiiik",
        "kiCCCCCCCCCCCCik",
        "kiCkCkCkCkCkCCik",
        "kiCCCCCCCCCCCCik",
        "kiCkCkCkCkCkCCik",
        "kiiiiiiiiiiiiiik",
        "kikppppppppeppik",
        "kiiiiiiiiiiiiiik",
        "kiikPkiiiikPkiik",
        "kiikkkiiiikkkiik",
        "kiiiiiiiiiiiiiik",
        ".kkkkkkkkkkkkkk.",
        "..kk........kk..",
    ],
    "title.task_hero": [  # the platform broom and its dustpan
        "..........kk....",
        ".........kik....",
        "........kik.....",
        ".......kik......",
        "......kik.......",
        ".....kik........",
        "....kik.........",
        "...kkkk.........",
        "..kpppppk.......",
        ".kpCpCpCpk......",
        "kpCpCpCpCpk.....",
        "kCpCpCpCpCk.kkkk",
        ".kkkkkkkkk.kllLk",
        "..........kllLLk",
        ".........kllllLk",
        ".........kkkkkkk",
    ],
    "title.grocery_runner": [  # the station lunchbox, tied with string, chopsticks tucked in
        "................",
        "..........kk....",
        ".........kCk....",
        "........kCk.....",
        ".kkkkkkkkkkkkkk.",
        "kiiiiiiieiiiiiik",
        "kiPPPPPPePPPPPik",
        "keeeeeeeeeeeeeek",
        "kiPPPPPPePPPPPik",
        "kiPPPPPPePPPPPik",
        "kkkkkkkkekkkkkkk",
        "krrrrrrrerrrrrrk",
        "krgggrrrerrpprrk",
        "krrrrrrrerrrrrrk",
        ".kkkkkkkkkkkkkk.",
        "................",
    ],
    "title.planner": [  # the platform clock, four o'clock
        ".......kk.......",
        ".......kk.......",
        ".....kkkkkk.....",
        "...kknnnnnnkk...",
        "..knnPPPPPPnnk..",
        ".knPPPPkPPPPPnk.",
        ".knPPPPkPPPPPnk.",
        "knPLPPPkPPPPLPnk",
        "knPPPPPePPPPPPnk",
        "knPPPPPPkPPPPPnk",
        ".knPPPPPPkPPPnk.",
        ".knPPPPPPPPPPnk.",
        "..knnPPLPPPPnk..",
        "...kknnnnnnkk...",
        ".....kkkkkk.....",
        "................",
    ],
    "title.wall_poet": [  # the chalk message board by the ticket gate
        "................",
        ".kkkkkkkkkkkkkk.",
        ".kiiiiiiiiiiiik.",
        ".kiggggggggggik.",
        ".kigPgPPggPgPik.",
        ".kiggPggPPgggik.",
        ".kigggggggggggk.",
        ".kigPPgPgPPgggk.",
        ".kiggggPggggpik.",
        ".kigPgPPggEEgik.",
        ".kiggggggggggik.",
        ".kiiiiiiiiiiiik.",
        ".kiPiEikkkkkkik.",
        ".kkkkkkkkkkkkkk.",
        "..kk........kk..",
        "..kk........kk..",
    ],
    "title.courier": [  # a parcel in brown paper, string and a luggage tag
        "................",
        "................",
        "....kkkkkkkkkk..",
        "...kCCCCCCkCCk..",
        "..kCCCCCCkCCCk..",
        ".kkkkkkkkkkkkkk.",
        ".kiiiiiikiiiiwk.",
        ".kiiiiiikiiiiwk.",
        ".kkkkkkkkkkkkwk.",
        ".kiiiiiikiiiiwk.",
        ".kiiiiiikiiiiwk.",
        ".kiiiiiikiiikkkk",
        ".kiiiiiikiiikPPk",
        ".kwwwwwwkwwwkPek",
        ".kkkkkkkkkkkkkk.",
        "................",
    ],
    "title.curator": [  # lost property: the umbrella nobody came back for
        ".......kk.......",
        ".....kkeekk.....",
        "...kkeEEeeekk...",
        "..keEEeeeeeerk..",
        ".keEeeeeeeeeerk.",
        ".kEeeeeeeeeeerk.",
        "keeerkeeerkeeerk",
        "kkkk.kkkk.kkkkk.",
        ".......kl.......",
        ".......kl.......",
        ".......kl.......",
        ".......kl.......",
        ".......kl.......",
        "....kk.kl.......",
        "....kiikk.......",
        ".....kkk........",
    ],
    "title.high_scorer": [  # the festival's prize: a goldfish in its bag
        ".......kk.......",
        "......keek......",
        ".......kk.......",
        "......kPPk......",
        ".....kmmmmk.....",
        "....kmmmmmmk....",
        "...kmmmmmmmmk...",
        "..kmmmEEEmmmmk..",
        "..kmmEEkEEmmEk..",
        "..kmmEEEEEEEEk..",
        "..kmmmEEEmmmEk..",
        "..kmmmmmmmmmmk..",
        "..kmmPmmmmmmmk..",
        "...kmmmmmmmmk...",
        "....kkkkkkkk....",
        "................",
    ],
    "title.collector": [  # the stamp-rally card, three stamps collected
        "................",
        ".kkkkkkkkkkkkkk.",
        ".kPPPPPPPPPPPPk.",
        ".kPccPPPPPPrrPk.",
        ".kcPPcPPPPrPPrk.",
        ".kcPcPPPPPrPrrk.",
        ".kPccPPPPPPrrPk.",
        ".kPPPPPPPPPPPPk.",
        ".kPPPPgggPPPPPk.",
        ".kPPPgPPPgPPPPk.",
        ".kPPPgPgPgPPPPk.",
        ".kPPPPgggPPCCPk.",
        ".kPPPPPPPPPCCPk.",
        ".kPPPPPPPPPPPPk.",
        ".kkkkkkkkkkkkkk.",
        "................",
    ],
    "title.game_hopper": [  # a kendama: the ball caught on the spike
        "......kkkk......",
        ".....keEEek.....",
        "....keEeeeek....",
        "....keeeeeek....",
        "....kreeeerk....",
        ".....krrrrk.....",
        ".......ik.......",
        "...kkkkiikkkk...",
        "...kiiiiiiiik...",
        "....kkkiikkk.k..",
        "......kiik...k..",
        ".....kiiiik..k..",
        ".....kiiiik.k...",
        "......kiik.k....",
        "......kiik......",
        ".......kk.......",
    ],
    "title.console_hopper": [  # the signal box's lever frame
        "................",
        "..kk....kk......",
        ".kEEk..kPPk.....",
        "..kk....kk....kk",
        "..kek...kl...kgk",
        "...kek..kl...kk.",
        "....kek.kl..kl..",
        ".....kekkl.kl...",
        "......kkkkkkk...",
        "..kkkkkkkkkkkkk.",
        ".kllllllllllllk.",
        ".klLLLLLLLLLLlk.",
        ".klkkklkkklkklk.",
        ".kllllllllllllk.",
        ".kkkkkkkkkkkkkk.",
        "................",
    ],
    "title.romhacker": [  # the ticket clipper's pliers, and the notch they cut
        "................",
        "...kk......kk...",
        "..kllk....kllk..",
        "..klLlk..klLlk..",
        "...kllk..kllk...",
        "....kllkkllk....",
        ".....kllllk.....",
        "......kLLk......",
        ".....klkklk.....",
        "....klk..klk....",
        "...kek....kek...",
        "..kek......kek..",
        ".kek........kek.",
        ".kek........kek.",
        "..k..........k..",
        "................",
    ],
}


def all_glyphs():
    out = {}
    for group in (NOX, AVATARS, ROOMS, TRANSPORT, MEDALS):
        out.update(group)
    for name, rows in out.items():
        assert len(rows) <= 16 and all(len(r) <= 16 for r in rows), name
        bad = {ch for r in rows for ch in r} - set(PALETTE) - {"."}
        assert not bad, (name, bad)
    return out
