"""The house's little drawings (sprites.json): Nox as a bat familiar, the five avatars, the room
marks, the transport keys, and 20 medals: the sub-weapons and relics of a vampire hunter.
Letters map to color.sprite.* tokens (data.py sets their colours). Light from the upper right.
    k outline  n Nox's shadow violet  l/L stone  m silver  c bone  C gold light  V gold  w gold dark
    e crimson  E crimson light  r crimson deep  v Nox's violet  g green  p candle  P flame  i holy water"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from jsonw import write  # noqa: E402

PALETTE = {"k": "outline", "n": "dark", "l": "mid-dark", "L": "mid", "m": "mist", "c": "light", "C": "light-dim",
           "e": "accent", "E": "accent-hi", "r": "accent-deep", "v": "familiar", "V": "familiar-mid",
           "w": "familiar-deep", "g": "good", "p": "alert", "P": "paper", "i": "ink"}

G = {}

# ---------- Nox, the familiar: a round little bat, ears high, eyes of candlelight ----------
NOX = [  # a bat: wings spread with finger ribs, ears up, candle eyes
    "................",
    ".....k....k.....",
    ".....kk..kk.....",
    ".....krkkrk.....",
    "k...kvvvvvvk...k",
    "kk..kvpvvpvk..kk",
    "knk.kvvvvvvk.knk",
    "knnkkvcvvcvkknnk",
    "knknkvvvvvvknknk",
    "knnknvvvvvvnknnk",
    "kknnkvvvvvvknnkk",
    "k.knk.kvvk.knk.k",
    "....k.kvvk.k....",
    ".......kk.......",
    "................",
    "................",
]
G["nox.idle"] = NOX
G["nox.blink"] = [r if i != 5 else "kk..kvkvvkvk..kk" for i, r in enumerate(NOX)]
G["nox.listening"] = [
    ".....k....k.....",
    ".....kk..kk.....",
    ".....krkkrk.....",
    ".....krvvrk.....",
    "k...kvvvvvvk...k",
    "kk..kvivvivk..kk",
    "knk.kvvvvvvk.knk",
    "knnkkvcvvcvkknnk",
    "knknkvvvvvvknknk",
    "knnknvvvvvvnknnk",
    "kknnkvvvvvvknnkk",
    "k.knk.kvvk.knk.k",
    "....k.kvvk.k....",
    ".......kk.......",
    "................",
    "................",
]
G["nox.thinking"] = [
    "...........m.m.m",
    ".....k....k.....",
    ".....kk..kk.....",
    ".....krkkrk.....",
    "k...kvvvvvvk...k",
    "kk..kvvmvvmk..kk",
    "knk.kvvvvvvk.knk",
    "knnkkvvvvvvkknnk",
    "knknkvvkkvvknknk",
    "knnknvvvvvvnknnk",
    "kknnkvvvvvvknnkk",
    "k.knk.kvvk.knk.k",
    "....k.kvvk.k....",
    ".......kk.......",
    "................",
    "................",
]
G["nox.happy"] = [
    "k..............k",
    "kk...k....k...kk",
    "knk..kk..kk..knk",
    "knnk.krkkrk.knnk",
    "knknkvvvvvvknknk",
    "knnnkvkvvkvknnnk",
    ".knnkvvvvvvknnk.",
    "..knkvcrrcvknk..",
    "...kkvvrrvvkk...",
    "....kvvvvvvk....",
    ".....kvvvvk.....",
    "......kvvk......",
    ".......kk.......",
    "................",
    "................",
    "................",
]
G["nox.error"] = [
    "................",
    "................",
    ".....k....k.....",
    ".....kk..kk.....",
    ".....krkkrk.....",
    "....kvvvvvvk....",
    "...kkvevvevkk...",
    "..knkvvvvvvknk..",
    ".knnkvvkkvvknnk.",
    "knknkvvvvvvknknk",
    "knnnkvvvvvvknnnk",
    "knnk.kvvvvk.knnk",
    "kkk..kvvvvk..kkk",
    "k.k...kvvk...k.k",
    ".......kk.......",
    "..............i.",
]

# ---------- the five pictures people pick (12 × 11 fills the ring; drawn at 16) ----------
G["avatar.moon"] = [
    "................",
    ".....kkkkkk.....",
    "...kkmmcccckk...",
    "..kmmmmmcccCck..",
    "..kmllmmmcccck..",
    ".kmllLmmmmcccck.",
    ".kmmLmmmmmmccck.",
    ".kmmmmmmllmmcck.",
    ".kmmmmmmlLmmmck.",
    ".kmmmllmmmmmmck.",
    ".kkmmlLmmmmmmck.",
    "..kmmmmmmmmmck..",
    "..kkmmmmmmmmkk..",
    "...kkkmmmmkkk...",
    ".....kkkkkk.....",
    "................",
]
G["avatar.bat"] = [
    "................",
    "................",
    "......k..k......",
    "......kkkk......",
    "k....kvvvvk....k",
    "kk..kvpvvpvk..kk",
    "knk.kvvvvvvk.knk",
    "knnkkvcvvcvkknnk",
    "knnnnvvvvvvnnnnk",
    "knnnnnvvvvnnnnnk",
    "kn.knnvvvvnnk.nk",
    "k...knkvvknk...k",
    "......k..k......",
    "................",
    "................",
    "................",
]
G["avatar.raven"] = [
    "................",
    "......kkkk......",
    ".....knnnnk.....",
    "....knnnnpnk....",
    "....knnnnnnkkkk.",
    "...knnnnnnnkmmmk",
    "...knnnnnnnkkkk.",
    "..knnnnnnnnk....",
    ".knnnlnnnnnk....",
    ".knnlnnnnnnnk...",
    "knnlnnnnnnnnk...",
    "knlnnnnnnnnk....",
    "knnnnnnnnkkk....",
    ".kkkknnkkwk.....",
    "....kwkk.kwk....",
    "....kVVVVVVVk...",
]
G["avatar.rose"] = [
    "................",
    ".....kkkkkk.....",
    "....kreeEEek....",
    "...kreErrEEek...",
    "...kerrEErrek...",
    "...kreEErrEek...",
    "....kreeeerk....",
    ".....kkrrkk.....",
    ".......kgk......",
    "...kk..kgk......",
    "..kggk.kgkkk....",
    "...kggkkgkggk...",
    "....kkkgkkkk....",
    ".......kgk......",
    ".......kgk......",
    "........k.......",
]
G["avatar.ghost"] = [
    "................",
    ".....kkkkkk.....",
    "....kmcccccck...",
    "...kmcccccccck..",
    "...kmckkcckkck..",
    "...kmckkcckkck..",
    "...kmcccccccck..",
    "...kmmccccccck..",
    "...kmmcckkccck..",
    "...kmmccccccck..",
    "...kmmmcccccck..",
    "...kmmmmcccccck.",
    "...kmmmmmccccck.",
    "...kmkmmkmcckck.",
    "...kk.kk.kkk.k..",
    "................",
]

# ---------- room marks ----------
G["room.home"] = [  # the keep
    ".......Cp.......",
    ".......kk.......",
    "......kLLk......",
    ".....kLLlLk.....",
    "....kLLLllLk....",
    "...kkkkkkkkkk...",
    "...kLkLkLkLmk...",
    "...kLLLLLLLmk...",
    "...kLLLkkLLmk...",
    "...kLLkppkLmk...",
    "...kLLkppkLmk...",
    "...kLLLLLLLmk...",
    "...kLLLkkLLmk...",
    "...kLLkrrkLmk...",
    "...kLLkrrkLmk...",
    "...kkkkkkkkkk...",
]
G["room.listen"] = [  # organ pipes
    "......kkkk......",
    "......kCVk......",
    "...kkkkCVkkkk...",
    "...kCVkCVkCVk...",
    "kkkkCVkCVkCVkkkk",
    "kCVkCVkCVkCVkCVk",
    "kCVkCVkCVkCVkCVk",
    "kkVkkVkkVkkVkkVk",
    "kCVkCVkCVkCVkCVk",
    "kwVkwVkwVkwVkwVk",
    "kkkkkkkkkkkkkkkk",
    "krrrrrrrrrrrrrek",
    "krkckckckckckcek",
    "krccccccccccccek",
    "krrrrrrrrrrrrrek",
    "kkkkkkkkkkkkkkkk",
]
G["room.watch"] = [  # a gilded frame with the moon in it
    "................",
    ".kkkkkkkkkkkkkk.",
    ".kVCCCCCCCCCCCk.",
    ".kVkkkkkkkkkkCk.",
    ".kVknnnnnnkmkCk.",
    ".kVknnnnnnmcmCk.",
    ".kVknnnnnnnmkCk.",
    ".kVknnnnnnnnkCk.",
    ".kVknnknnnnnkCk.",
    ".kVknkkknnnnkCk.",
    ".kVkkkkkkknnkCk.",
    ".kVkkkkkkkkkkCk.",
    ".kwVVVVVVVVVVVk.",
    ".kkkkkkkkkkkkkk.",
    "......kwwk......",
    ".....kkkkkk.....",
]
G["room.house"] = [  # a skeleton key
    "................",
    "...kkkk.........",
    "..kCVVCk........",
    ".kCkkkkVk.......",
    ".kVk..kVk.......",
    ".kVk..kVk.......",
    ".kVkkkkwk.......",
    "..kVwwwkkk......",
    "...kkkkVwk......",
    ".......kVwk.....",
    "........kVwk....",
    ".........kVwkkk.",
    "..........kVwVk.",
    "...........kVkk.",
    "..........kVwVk.",
    "...........kkkk.",
]
G["room.files"] = [  # a tome with a clasp
    "................",
    "..kkkkkkkkkkk...",
    ".kreeeeeeeeeEk..",
    ".kreeeeeeeeeEkk.",
    ".kreeeCCCeeeEkck",
    ".kreeCkkkCeeEkck",
    ".kreeCkeeCeeEkck",
    ".kreeeCCCeeeEVVk",
    ".kreeeeeeeeeEVkk",
    ".kreeeeCeeeeEkck",
    ".kreeeCeCeeeEkck",
    ".kreeeeCeeeeEkck",
    ".kreeeeeeeeeEkck",
    ".krrrrrrrrrrrkck",
    "..kkkkkkkkkkkkck",
    "...kkkkkkkkkkkk.",
]
G["room.smart-home"] = [  # a lantern
    "................",
    "......kkkk......",
    ".....kk..kk.....",
    "......kkkk......",
    ".....kVVCCk.....",
    "....kkkkkkkk....",
    "....kwkppkVk....",
    "....kwpPppVk....",
    "....kwpPPpVk....",
    "....kwkPpkVk....",
    "....kwkppkVk....",
    "....kkkkkkkk....",
    ".....kVVCCk.....",
    "......kkkk......",
    "................",
    "................",
]
G["room.games"] = [  # a treasure chest
    "................",
    "................",
    "...kkkkkkkkkk...",
    "..krrrrkkrrrrk..",
    ".krrrrkCCkrrrrk.",
    ".kVVVVkCCkVVVCk.",
    ".kkkkkkkkkkkkkk.",
    ".krrrrkppkrrrrk.",
    ".krrrrkpPkrrrek.",
    ".krrrrrkkrrrrek.",
    ".kVVVVVVVVVVVCk.",
    ".krrrrrrrrrrrek.",
    ".krrrrrrrrrrrek.",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
]
G["room.me"] = [  # a cameo: a profile in an oval of gold
    "................",
    ".....kkkkkk.....",
    "....kVCCCCCk....",
    "...kVkkkkkkCk...",
    "..kVkrrrcccrkCk.",
    "..kVkrrcccccrCk.",
    "..kVkrrccccrrCk.",
    "..kVkrrrccccrCk.",
    "..kVkrrrrccrrCk.",
    "..kVkrrrcccrrCk.",
    "..kVkrrccccccCk.",
    "...kVkkkkkkkCk..",
    "....kwVVVVCCk...",
    ".....kkkkkkk....",
    "......kCCk......",
    ".......kk.......",
]
G["room.more"] = [  # a gothic door, studded
    "......kkkk......",
    "....kkwVVCkk....",
    "...kwVVkkVVCk...",
    "..kwVVkrrkVVCk..",
    "..kwVkrrrrkVCk..",
    ".kwVkrrrrrrkVCk.",
    ".kwVkrerrerkVCk.",
    ".kwVkrrrrrrkVCk.",
    ".kwVkrrrrrrkVCk.",
    ".kwVkrerrprkVCk.",
    ".kwVkrrrrrrkVCk.",
    ".kwVkrrrrrrkVCk.",
    ".kwVkrerrerkVCk.",
    ".kwVkrrrrrrkVCk.",
    ".kwVkrrrrrrkVCk.",
    "kkkkkkkkkkkkkkkk",
]

# ---------- transport keys, 9 × 9: gold on a dark outline ----------
G["transport.play"] = [
    "kk.......",
    "kCkk.....",
    "kCCCkk...",
    "kCCCCCkk.",
    "kCCCCCCCk",
    "kVVVVVkk.",
    "kVVVkk...",
    "kVkk.....",
    "kk.......",
]
G["transport.pause"] = [
    "kkkk.kkkk",
    "kCCk.kCCk",
    "kCCk.kCCk",
    "kCCk.kCCk",
    "kCCk.kCCk",
    "kVVk.kVVk",
    "kVVk.kVVk",
    "kVVk.kVVk",
    "kkkk.kkkk",
]
G["transport.next"] = [
    "kk....kkk",
    "kCkk..kCk",
    "kCCCkkkCk",
    "kCCCCCkCk",
    "kCCCCCCCk",
    "kVVVVVkVk",
    "kVVVkkkVk",
    "kVkk..kVk",
    "kk....kkk",
]
G["transport.previous"] = [
    "kkk....kk",
    "kCk..kkCk",
    "kCkkkCCCk",
    "kCkCCCCCk",
    "kCCCCCCCk",
    "kVkVVVVVk",
    "kVkkkVVVk",
    "kVk..kkVk",
    "kkk....kk",
]
G["transport.stop"] = [
    "kkkkkkkkk",
    "kcCCCCCVk",
    "kCCCCCCwk",
    "kCCVVVCwk",
    "kCCVeVCwk",
    "kCCVVVCwk",
    "kCCCCCCwk",
    "kVwwwwwwk",
    "kkkkkkkkk",
]

# ---------- medals: the hunter's sub-weapons and relics ----------
G["title.dj"] = [  # a lute
    "...........kk...",
    "..........kwVk..",
    "..........kVk...",
    ".........kwk....",
    "........kwk.....",
    ".......kwk......",
    "......kwk.......",
    "....kkwVkk......",
    "...kVVcVVCk.....",
    "..kVVVcVVCCk....",
    "..kVVkckVVCk....",
    ".kVVkkckkVVCk...",
    ".kVVVkkkVVVCk...",
    ".kwVVVcVVVVCk...",
    "..kwwVVVVVCk....",
    "...kkkkkkkk.....",
]
G["title.explorer"] = [  # a lantern held high
    "......k.........",
    ".....kPk..k.....",
    "....kPpPkkPk....",
    "....kPppPPPk....",
    "...kPpccpPk.....",
    "...kPpcppPk.....",
    "....kPPPPk......",
    ".....kwwk.......",
    ".....kVVk.......",
    ".....kwVk.......",
    "......kwVk......",
    "......kwVk......",
    ".......kwVk.....",
    ".......kwVk.....",
    "........kwk.....",
    ".........k......",
]
G["title.night_owl"] = [  # a crescent moon amulet
    "................",
    ".......kk.......",
    "......kCCk......",
    ".....kkkkkk.....",
    "....kmcck.......",
    "...kmcck........",
    "..kmmck.........",
    "..kmmck......k..",
    "..kmmck.....kpk.",
    "..kmmmck.....k..",
    "...kmmcck.......",
    "....kmmccckkk...",
    ".....kmmmcccck..",
    "......kkmmmmk...",
    "........kkkk....",
    "................",
]
G["title.early_bird"] = [  # the sun medallion: dawn, dreaded and faced
    ".......kk.......",
    "...k...kpk...k..",
    "...kk..kpk..kk..",
    "....kkkkkkkkk...",
    "...kkpppppppkk..",
    "kkkppPPPPPPppkkk",
    "kppkpPpPPpPpkppk",
    ".kkppPPPPPPppkk.",
    "..kppPPkkPPppk..",
    "..kkppPPPPppkk..",
    "..kkkppppppkkk..",
    "..kk.kkkkkk.kk..",
    "..k...kpk....k..",
    ".......kpk......",
    ".......kk.......",
    "................",
]
G["title.weekend"] = [  # a chalice of wine
    "................",
    "..kkkkkkkkkkkk..",
    "..kCrrrrrrrreCk.",
    "..kVCrrrrrreCVk.",
    "...kVCCCCCCCVk..",
    "...kwVVVVVVVwk..",
    "....kwVVVVVwk...",
    ".....kwVVVwk....",
    "......kwVk......",
    "......kwCk......",
    "......kwCk......",
    ".....kwVCk......",
    "....kwVVVCk.....",
    "...kwVVVVVCk....",
    "...kkkkkkkkk....",
    "................",
]
G["title.genre_guardian"] = [  # a shield with a cross
    "................",
    ".kkkkkkkkkkkkkk.",
    ".kCCCCCCCCCCCCk.",
    ".kVrrrrkCkeeeCk.",
    ".kVrrrrkCkeeeCk.",
    ".kVkkkkkCkkkkCk.",
    ".kVCCCCCCCCCCCk.",
    ".kVkkkkkCkkkkCk.",
    ".kVrrrrkCkeeeCk.",
    "..kVrrrkCkeeCk..",
    "..kVrrrkCkeeCk..",
    "...kVrrkCkeCk...",
    "....kVrkCkCk....",
    ".....kVkCCk.....",
    "......kkkk......",
    "................",
]
G["title.broken_record"] = [  # the stopwatch: the same song, stopped in time
    "......kkkk......",
    "......kCVk......",
    ".....kkkkkk.....",
    "...kkVVVVCCkk...",
    "..kVVkkkkkkCCk..",
    ".kVVkccckccckCk.",
    ".kVkcccckcccckCk",
    "kVVkcccckcccckCk",
    "kVkccccckkkcckCk",
    "kVkcccccccccckCk",
    "kVVkcccccccccCk.",
    ".kVkccccccccckk.",
    ".kVVkkcccccckk..",
    "..kwVVkkkkkVk...",
    "...kkwwVVVkk....",
    ".....kkkkk......",
]
G["title.marathon"] = [  # an hourglass
    "..kkkkkkkkkkkk..",
    "..kwVVVVVVVVCk..",
    "...kkkkkkkkkk...",
    "...kmcccccccmk..",
    "...kmpppppppk...",
    "....kmpppppk....",
    ".....kmpppk.....",
    "......kmpk......",
    "......kmck......",
    ".....kmcpck.....",
    "....kmcccpck....",
    "...kmcccppppk...",
    "...kmcpppppppk..",
    "...kkkkkkkkkk...",
    "..kwVVVVVVVVCk..",
    "..kkkkkkkkkkkk..",
]
G["title.radio_host"] = [  # a chapel bell
    "......kkkk......",
    "......kwCk......",
    ".....kkkkkk.....",
    "....kwVVVCCk....",
    "...kwVVVVCCCk...",
    "...kwVVVVVCCk...",
    "...kwVVVVVCCk...",
    "..kwVVVVVVVCCk..",
    "..kwVVVVVVVCCk..",
    ".kwVVVVVVVVVCCk.",
    ".kwwVVVVVVVVVCk.",
    "kkkkkkkkkkkkkkkk",
    "kwwwwwVVVVVVVCCk",
    "kkkkkkkkkkkkkkkk",
    ".......kVk......",
    "........k.......",
]
G["title.task_hero"] = [  # the double-bitted throwing axe
    "................",
    ".kk....kk....kk.",
    "kmck...kVk..kcmk",
    "kmmck..kVk.kcmmk",
    "kmmmckkkVkkcmmmk",
    "kmmmmmmCVmmmmmmk",
    "kmmmmmmCVmmmmmmk",
    "kLmmckkkVkkcmmLk",
    "kLmck..kVk..kcLk",
    ".kk....kVk....kk",
    ".......kVk......",
    ".......kVk......",
    ".......kVk......",
    "......kwVwk.....",
    "......kkkkk.....",
    "................",
]
G["title.grocery_runner"] = [  # the roast found in the wall
    "................",
    "................",
    "....kkkkkk......",
    "...kPPPPPPkk....",
    "..kPpPPPPPPPk...",
    ".kPpPPPPPPPPPk..",
    ".kPPPPPPPrPPPk..",
    ".kPPPPPPPPPPPk..",
    ".krPPPPPrPPPrkk.",
    "..krrPPPPPrrkcck",
    "...krrrrrrrkccck",
    "....kkkkkkkkcck.",
    "...........kcck.",
    "............kk..",
    "................",
    "................",
]
G["title.planner"] = [  # a grimoire, open
    "................",
    "................",
    ".kkkkkk..kkkkkk.",
    "kccccccckcccccck",
    "kcllllcckcllllck",
    "kcccccccVcccccck",
    "kcllllccVcllllck",
    "kcccccccVcccccck",
    "kclllcccVclllcck",
    "kcccccccVcccccck",
    "kcllllccVcllllck",
    "kccccccckcccccck",
    "krrrrrrrkrrrrrrk",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
]
G["title.wall_poet"] = [  # a quill in its inkwell
    "............kkk.",
    "...........kccck",
    "..........kcmcck",
    ".........kcmcck.",
    "........kcmcck..",
    ".......kcmcck...",
    "......kcmck.....",
    ".....kcmck......",
    "....kkmck.......",
    "....kkck........",
    "...kkkk.........",
    "..kkrrrkk.......",
    ".krrerrrrk......",
    ".krrrrrrrk......",
    ".kVVVVVVCk......",
    "..kkkkkkk.......",
]
G["title.courier"] = [  # the dagger, thrown
    "................",
    "................",
    "................",
    "................",
    "..........k.....",
    "kk.......kVk....",
    "kmkkkkkkkkVkkk..",
    "kmmccccccckVwwkk",
    "kmmmmmmmmmkVwwkk",
    "kmkkkkkkkkVkkk..",
    "kk.......kVk....",
    "..........k.....",
    "................",
    "................",
    "................",
    "................",
]
G["title.curator"] = [  # a key ring
    "................",
    "....kkkkk.......",
    "...kVkkkCk......",
    "..kVk...kCk.....",
    "..kVk...kCk.....",
    "..kwVkkkVCk.....",
    "...kwVVVCkk.....",
    "....kkkkkVk.....",
    "........kVwk....",
    "........kVwk....",
    "........kVwkk...",
    "........kVwwVk..",
    "........kVwkk...",
    "........kVwwVk..",
    "........kkkkk...",
    "................",
]
G["title.high_scorer"] = [  # a crown
    "................",
    "................",
    "..k....kk....k..",
    ".kCk..kCCk..kCk.",
    ".kCk..kCCk..kCk.",
    ".kVCk.kVCk.kVCk.",
    ".kVCkkVVCCkkVCk.",
    ".kVVCVVVVCCVVCk.",
    ".kVkkkVVCkkkVCk.",
    ".kVkekVVCkikVCk.",
    ".kVkkkVVCkkkVCk.",
    ".kwVVVVVVVVVVCk.",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
    "................",
]
G["title.collector"] = [  # the big heart
    "................",
    "..kkkk....kkkk..",
    ".keeeEk..keEEEk.",
    "kreeeeEkkeeeEcEk",
    "kreeeeeeeeeeEEEk",
    "kreeeeeeeeeeeEEk",
    "krreeeeeeeeeeeEk",
    "krreeeeeeeeeeeek",
    ".krreeeeeeeeeek.",
    "..krreeeeeeeek..",
    "...krreeeeeek...",
    "....krreeeek....",
    ".....krreek.....",
    "......krrk......",
    ".......kk.......",
    "................",
]
G["title.game_hopper"] = [  # the holy water vial
    "................",
    "......kkkk......",
    "......kcck......",
    ".......kk.......",
    "......kmmk......",
    ".....kmmmmk.....",
    "....kmiiiiimk...",
    "...kmiiiiiiimk..",
    "...kmiicciiimk..",
    "...kmicciiiimk..",
    "...kmiiiiiiimk..",
    "...kmiiiiiiimk..",
    "....kmiiiiimk...",
    ".....kkkkkkk....",
    "................",
    "................",
]
G["title.console_hopper"] = [  # the cross, thrown and returning
    "......kkkk......",
    "......kCVk......",
    "......kCVk......",
    "......kCVk......",
    "..kkkkkCVkkkkk..",
    "..kCCCCCCCCCCk..",
    "..kVVVVCVVVVVk..",
    "..kkkkkCVkkkkk..",
    "......kCVk......",
    "......kCVk......",
    "......kCVk......",
    "......kCVk......",
    "......kCVk......",
    "......kwwk......",
    "......kkkk......",
    "................",
]
G["title.romhacker"] = [  # the crystal orb
    "................",
    ".....kkkkkk.....",
    "...kkimmmmikk...",
    "..kimmcciiimik..",
    "..kimcciiiiiik..",
    ".kimcciiiiiiiik.",
    ".kimciiieiiiiik.",
    ".kiiiiieEeiiiik.",
    ".kiiiiiieiiiiik.",
    ".kiiiiiiiiiiiik.",
    "..kiiiiiiiiiik..",
    "..kkiiiiiiiikk..",
    "...kwkkkkkkVk...",
    "..kwVVVVVVVVCk..",
    "..kkkkkkkkkkkk..",
    "................",
]


def check():
    for k, rows in G.items():
        w = len(rows[0])
        assert all(len(r) == w for r in rows), (k, [len(r) for r in rows])
        assert len(rows) <= 16 and w <= 16, k
        bad = {ch for r in rows for ch in r if ch != "." and ch not in PALETTE}
        assert not bad, (k, bad)


def main():
    check()
    theme = HERE.parents[3] / "themes" / "night-castle"
    write(theme / "sprites.json", {
        "$schema": "../_schema/sprites.schema.json",
        "$description": "The Vampire's Keep: Nox as a bat familiar, bat/raven/rose/ghost/moon avatars, castle room marks, gold HUD transport keys, and the hunter's relics as medals. Drawn by code (docs/design/themes/night-castle/pieces.py), CC-BY-4.0.",
        "palette": PALETTE,
        "glyphs": G,
    })
    print(len(G), "pieces")


if __name__ == "__main__":
    main()
