"""Themes → CSS. Base goes in the `tokens` layer on `:root` (so an unknown or missing theme still
draws), every other theme in the `theme` layer on `[data-theme="<id>"]`; each block is complete."""

import hashlib
import json
import re
from pathlib import Path

from . import tokens as t

GENERATED = Path(__file__).resolve().parents[3] / "frontend/src/design/generated"
HEADER = "Generated by `python3 -m houseos.theme_kit build` from themes/. Do not edit."
DEFAULT = "zabiwa"
# The pickers' order: Zabiwa first, then the calm themes, the worlds, and Legacy last (any other
# bundled theme after them).
PICKER = ("zabiwa", "pure", "modular", "linen-morning", "y2k", "night-castle", "pocket-hatchling",
          "sento-night", "showa-platform", "carved-night")  # fmt: skip


def bundled(root: Path | None = None) -> list[t.Theme]:
    root = root or t.ROOT
    found = sorted(
        p.name
        for p in root.iterdir()
        if p.is_dir() and not p.name.startswith("_") and (p / "theme.json").exists()
    )
    return [t.load(name, root) for name in sorted(found, key=lambda n: (n != "base", PICKER.index(n) if n in PICKER else len(PICKER), n))]


def block(selector: str, values: dict[str, str], scheme: str | None = None) -> str:
    lines = [f"  {name}: {value};" for name, value in values.items()]
    if scheme:
        lines.insert(0, f"  color-scheme: {scheme};")
    return selector + " {\n" + "\n".join(lines) + "\n}\n"


ART = re.compile(r"url\(\s*([\"']?)art/")


def theme_css(theme: t.Theme, base: t.Theme, art: str = "") -> str:
    """One theme's rules (all its schemes and rooms), unwrapped. `art`: where its art/ is served,
    so a texture's url(art/…) finds its file."""
    out = []
    for index, scheme in enumerate(theme.schemes):
        values = t.variables(theme, scheme, base)
        values = {k: ART.sub(lambda m: f"url({m[1]}{art}art/", v) for k, v in values.items()}
        scheme_part = "" if index == 0 else f'[data-scheme="{scheme}"]'
        if theme.id == base.id:
            owners = [f":root{scheme_part}", f'[data-theme="base"]{scheme_part}']
        else:
            owners = [f'[data-theme="{theme.id}"]{scheme_part}']
        out.append(block(", ".join(owners), values, scheme))
        for room, room_values in t.room_variables(values).items():
            out.append(block(", ".join(f'{o}[data-room="{room}"]' for o in owners), room_values))
    return "\n".join(out)


# Fontsource's subsets: the ranges a browser uses to fetch only the file it needs.
RANGES = {
    "latin": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, "
    "U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "latin-ext": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, "
    "U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, "
    "U+2C60-2C7F, U+A720-A7FF",
}
FONT_FILE = re.compile(r"(.+?)-(latin-ext|latin)-(\d{3})-(normal|italic)\.woff2")


def font_faces(theme: t.Theme, url: str) -> str:
    """@font-face for the theme's own fonts/ files, served at `url` + file name."""
    folder = theme.folder / "fonts"
    families = {re.sub(r"[^a-z0-9]+", "-", f.lower()).strip("-"): f for f in theme.manifest["fonts"].values()}
    faces = []
    for font in sorted(folder.glob("*.woff2")) if folder.is_dir() else []:
        found = FONT_FILE.fullmatch(font.name)
        if found and found[1] in families:
            faces.append(
                f'@font-face {{ font-family: "{families[found[1]]}"; font-style: {found[4]}; '
                f"font-weight: {found[3]}; font-display: swap; src: url({url}{font.name}) "
                f'format("woff2"); unicode-range: {RANGES[found[2]]}; }}\n'
            )
    return "".join(faces)


def stylesheet(themes: list[t.Theme]) -> str:
    base = themes[0]
    parts = [f"/* {HEADER} */\n", "@layer tokens {\n" + indent(theme_css(base, base)) + "}\n"]
    rest = [indent(theme_css(theme, base, f"../../../../themes/{theme.id}/")) for theme in themes[1:]]
    if rest:
        parts.append("@layer theme {\n" + "\n".join(rest) + "}\n")
    # A bundled theme's own fonts, from its folder (Vite bundles them from this relative path).
    parts += [font_faces(theme, f"../../../../themes/{theme.id}/fonts/") for theme in themes]
    return "\n".join(part for part in parts if part)


def indent(css: str) -> str:
    return "".join("  " + line if line.strip() else line for line in css.splitlines(keepends=True))


def entry(theme: t.Theme, base: t.Theme) -> dict:
    """What the interface knows of one theme (the picker's names, swatches, slots and words)."""
    m = theme.manifest
    swatches = {}
    for scheme in theme.schemes:
        v = t.variables(theme, scheme, base)
        swatches[scheme] = [v[k] for k in SWATCHES]
    return {
        "id": theme.id,
        "names": m["names"],
        "description": m["description"],
        "schemes": theme.schemes,
        "hidden": bool(m.get("hidden")),
        "identity": m.get("identity", "line"),
        "slots": m.get("slots", {}),
        "layers": m.get("layers", []),
        "credit": m.get("credit"),
        # The pickers' card: the tour's picture of Home in each scheme (art/card-<scheme>.webp).
        "cards": {s: f"art/card-{s}.webp" for s in theme.schemes if (theme.folder / f"art/card-{s}.webp").is_file()},
        "parts": {**PARTS_DEFAULT, **(m.get("parts") or {})},
        "sprites": sprite_grids(theme),
        "flavor": {k: v for k, v in t.read(theme.folder / "flavor.json").items() if not k.startswith("$")},
        "swatches": swatches,
    }


PARTS_DEFAULT = {
    part: spec["default"]
    for part, spec in t.read(t.ROOT / "_schema/parts.json").items()
    if not part.startswith("$")
}


def sprite_grids(theme: t.Theme) -> dict:
    """The pieces this theme redraws (sprites.json as checked): its palette, letter → color.sprite
    token, and its grids by piece id. The app paints them in the theme's colours."""
    data = t.read(theme.folder / "sprites.json")
    if not data:
        return {}
    return {"palette": data.get("palette", {}), "glyphs": data.get("glyphs", {})}


# What a picker's card shows: the ground, the ink, the accent, a state and a room that is not
# the accent (Listen often is), so five dots say five different things.
SWATCHES = (
    "--c-bg-canvas",
    "--c-fg-default",
    "--c-accent-solid",
    "--c-success-solid",
    "--c-room-watch",
)


def poke_at(poke: dict, at) -> dict:
    burst = poke.get("burst")
    return {**poke, **({"image": at(poke["image"])} if "image" in poke else {}),
            **({"burst": {**burst, "image": at(burst["image"])}} if burst else {})}  # fmt: skip


def served(info: dict, where: str, folder: Path | None = None) -> dict:
    """A theme's entry with its pictures (slots, rooms' pictures, layers) where the app serves its
    art/: `where` is "/themes/bundled/<id>/" for a bundled theme, "/themes/<id>/" for an installed one.
    With the theme's `folder`, each picture's address carries a fingerprint of its content
    (?v=…): a picture redrawn under the same name is fetched again, never mixed with a cached one."""

    def at(path: str) -> str:
        if not path.startswith("art/"):
            return path
        file = folder / path if folder else None
        mark = f"?v={hashlib.sha256(file.read_bytes()).hexdigest()[:10]}" if file and file.is_file() else ""
        return where + path + mark

    def fill_at(fill):
        if isinstance(fill, str):
            return at(fill)
        if isinstance(fill, dict) and "image" in fill:
            at_any = lambda file: at(file) if isinstance(file, str) else {s: at(f) for s, f in file.items()}  # noqa: E731
            more = {key: {k: at_any(file) for k, file in fill[key].items()} for key in ("rooms", "schemes") if key in fill}
            return {**fill, "image": at(fill["image"]), **more}
        return fill

    return info | {
        "cards": {scheme: at(file) for scheme, file in info.get("cards", {}).items()},
        "slots": {slot: fill_at(fill) for slot, fill in info["slots"].items()},
        "layers": [{**layer, "image": at(layer["image"]), **({"poke": poke_at(layer["poke"], at)} if "poke" in layer else {})}
                   for layer in info["layers"]],
    }


def registry(themes: list[t.Theme]) -> str:
    base = themes[0]
    entries = [served(entry(theme, base), f"/themes/bundled/{theme.id}/", theme.folder) for theme in themes]
    return (
        f"// {HEADER}\n"
        'export type Scheme = "dark" | "light";\n'
        'export type SlotFill =\n  | { scene: "hall" | "room" }\n  | string\n'
        '  | { image: string; rendering?: "pixel" | "smooth"; fit?: "cover" | "contain" | "stretch" | "slice"; slice?: number; anchor?: "top" | "center" | "bottom"; rooms?: Record<string, string | Partial<Record<Scheme, string>>>; schemes?: Partial<Record<Scheme, string>> };\n'
        "/** A picture the app moves (themes/README.md, Layers; checked by theme_kit). */\n"
        "export type Layer = {\n  image: string;\n"
        '  where: "page" | "hero" | "header" | "rail" | "rail-foot" | "status" | "deck";\n'
        "  rooms?: string[];\n  schemes?: Scheme[];\n"
        '  fit?: "cover" | "contain" | "repeat" | "repeat-x" | "natural";\n'
        '  anchor?: "center" | "top" | "bottom" | "left" | "right" | "top-left" | "top-right" | "bottom-left" | "bottom-right";\n'
        '  blend?: "normal" | "screen" | "multiply" | "overlay" | "soft-light";\n'
        '  rendering?: "pixel" | "smooth";\n'
        "  scale?: number;\n  opacity?: number;\n  above?: boolean;\n  under?: boolean;\n  depth?: number;\n"
        "  drift?: [number, number];\n"
        '  cross?: { seconds: number; every?: number; from?: "left" | "right" | "top" | "bottom" };\n'
        "  frames?: { count: number; fps?: number };\n"
        '  particles?: { count: number; motion: "rise" | "fall" | "float" | "twinkle"; seconds?: number };\n'
        "  playing?: boolean;\n"
        "  poke?: { image?: string; frames: { count: number; fps?: number }; burst?: { image: string; count: number }; stay?: \"random\" };\n};\n"
        "export type ThemeInfo = {\n  id: string;\n  names: { en: string; fr: string };\n"
        "  description: { en: string; fr: string };\n  schemes: Scheme[];\n  hidden: boolean;\n"
        '  identity: "pixel" | "line";\n'
        "  slots: Record<string, SlotFill>;\n"
        "  layers: Layer[];\n"
        "  credit?: { en: string; fr: string } | null;\n"
        "  cards?: Partial<Record<Scheme, string>>;\n"
        "  parts: Record<string, string>;\n"
        "  sprites: { palette?: Record<string, string>; glyphs?: Record<string, string[]> };\n"
        "  flavor: Record<string, { en: string; fr: string }>;\n"
        "  swatches: Partial<Record<Scheme, string[]>>;\n};\n"
        f"export const DEFAULT_THEME = {json.dumps(DEFAULT)};\n"
        f"export const THEMES: ThemeInfo[] = {json.dumps(entries, indent=2, ensure_ascii=False)};\n"
        f"/** Every art slot (themes/_schema/slots.json). */\n"
        f"export const SLOTS = {json.dumps(slot_catalogue(), indent=2, ensure_ascii=False)} as const;\n"
        f"/** Every part and its variants (themes/_schema/parts.json). */\n"
        f"export const PARTS = {json.dumps(catalogue_of('parts.json'), indent=2, ensure_ascii=False)} as const;\n"
        f"/** Every piece a theme may redraw (themes/_schema/sprites.ids.json). */\n"
        f"export const PIECES = {json.dumps(catalogue_of('sprites.ids.json'), indent=2, ensure_ascii=False)} as const;\n"
    )


def catalogue_of(name: str) -> dict:
    return {k: v for k, v in t.read(t.ROOT / "_schema" / name).items() if not k.startswith("$")}


def slot_catalogue() -> dict:
    return {k: v for k, v in t.read(t.ROOT / "_schema/slots.json").items() if not k.startswith("$")}


def token_schema(base: t.Theme) -> str:
    """themes/_schema/tokens.schema.json: every name a theme may set (a typo or a fixed token is
    refused by an editor as well as by the checks), made from the catalogue so it never drifts."""
    tree: dict = {}
    for row in t.catalogue(base):
        if row["themeable"] == "no":
            continue
        node = tree
        for part in row["token"].split(".")[:-1]:
            node = node.setdefault(part, {})
        node[row["token"].split(".")[-1]] = row["description"]

    def schema(node):
        if isinstance(node, str):
            return {
                "type": "object",
                "description": node,
                "required": ["$value"],
                "properties": {"$value": {}, "$type": {"type": "string"}, "$description": {"type": "string"}},
                "additionalProperties": False,
            }
        props = {key: schema(child) for key, child in node.items()}
        return {
            "type": "object",
            "properties": {"$type": {"type": "string"}, "$description": {"type": "string"}, **props},
            "additionalProperties": False,
        }

    top = schema(tree)
    top["properties"]["$schema"] = {"type": "string"}
    return (
        json.dumps(
            {
                "$schema": "https://json-schema.org/draft/2020-12/schema",
                "$comment": HEADER,
                "title": "A HouseOS theme's tokens.json (DTCG): only what differs from Base",
                **top,
            },
            indent=1,
            ensure_ascii=False,
        )
        + "\n"
    )


def manifest_schema() -> str:
    """themes/_schema/theme.schema.json with its parts, slot fills and layers made from what the
    checks accept (parts.json, check.LAYER), so an editor's hints never drift from the kit."""
    from . import check

    schema = json.loads((t.ROOT / "_schema/theme.schema.json").read_text())
    props = schema["properties"]
    props.pop("motion", None)
    props["credit"] = {"$ref": "#/$defs/words", "description": "Who made it, shown small at the rail's foot: plain text, 40 characters at most, never a link."}
    props["parts"]["properties"] = {
        part: {"enum": list(spec["variants"]), "default": spec["default"],
               "description": "; ".join(f"{name}: {what}" for name, what in spec["variants"].items())}
        for part, spec in catalogue_of("parts.json").items()
    }  # fmt: skip
    image = props["slots"]["additionalProperties"]["oneOf"][2]["properties"]
    image["fit"]["enum"] = ["cover", "contain", "stretch", "slice"]
    image["slice"] = {"type": "integer", "minimum": 1, "maximum": 400, "description": "With fit slice (surfaces): the frame's corner size in px."}
    picture = {"type": "string", "pattern": image["image"]["pattern"]}
    image["rooms"] = {"type": "object", "propertyNames": {"enum": list(t.ALL_ROOMS)},
                      "additionalProperties": {"oneOf": [picture, {"type": "object", "additionalProperties": picture,
                                                                   "propertyNames": {"enum": list(t.SCHEMES)}}]},
                      "description": "Another picture in these rooms: {room: art/<file>} or {room: {dark|light: art/<file>}}."}  # fmt: skip
    image["schemes"] = {"type": "object", "propertyNames": {"enum": list(t.SCHEMES)},
                        "additionalProperties": {"type": "string", "pattern": image["image"]["pattern"]},
                        "description": "Another picture in this scheme: {dark|light: art/<file>} (a room's own wins)."}  # fmt: skip
    number = lambda low, high: {"type": "number", "minimum": low, "maximum": high}  # noqa: E731
    props["layers"] = {
        "type": "array", "maxItems": check.LAYERS_MAX,
        "description": "Pictures the app moves, as far as the person's motion level allows (themes/README.md, Layers).",
        "items": {"type": "object", "required": ["image", "where"], "additionalProperties": False, "properties": {
            "image": image["image"],
            **{key: {"enum": list(allowed)} for key, allowed in check.LAYER.items()},
            "rooms": {"type": "array", "items": {"enum": list(t.ALL_ROOMS)}},
            "schemes": {"type": "array", "items": {"enum": list(t.SCHEMES)}},
            "scale": {"type": "integer", "minimum": 1, "maximum": 8},
            "opacity": number(0.05, 1), "depth": number(0, 1),
            "above": {"type": "boolean", "description": f"Over the page (where page), opacity {check.ABOVE_OPACITY} at most."},
            "under": {"type": "boolean", "description": "Behind the place's own picture (page, hero, status, header), e.g. a sky seen through it."},
            "drift": {"type": "array", "items": number(-200, 200), "minItems": 2, "maxItems": 2},
            "cross": {"type": "object", "additionalProperties": False, "properties": {
                "seconds": number(2, 120), "every": number(2, 600), "from": {"enum": list(check.CROSS_FROM)}}},
            "frames": {"type": "object", "additionalProperties": False, "properties": {
                "count": {"type": "integer", "minimum": 2, "maximum": 32}, "fps": number(1, 24)}},
            "particles": {"type": "object", "additionalProperties": False, "properties": {
                "count": {"type": "integer", "minimum": 1, "maximum": 24},
                "motion": {"enum": list(check.PARTICLE_MOTION)}, "seconds": number(2, 60)}},
            "playing": {"type": "boolean"},
            "poke": {"type": "object", "additionalProperties": False, "required": ["frames"],
                     "description": "Desktop: a click plays this reaction once (a natural piece), with an optional small burst.",
                     "properties": {"image": image["image"], "frames": {"type": "object", "additionalProperties": False, "properties": {
                         "count": {"type": "integer", "minimum": 2, "maximum": 32}, "fps": number(1, 24)}},
                         "stay": {"enum": ["random"], "description": "After the reaction, the piece keeps one of its frames at random (a new arrangement each click)."},
                         "burst": {"type": "object", "additionalProperties": False, "required": ["image", "count"], "properties": {
                             "image": image["image"], "count": {"type": "integer", "minimum": 1, "maximum": check.BURST_MAX}}}}},
        }},
    }  # fmt: skip
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


def build(root: Path | None = None, out: Path = GENERATED) -> dict[str, str]:
    """The generated files by name (written when `out` is given; the schema beside the themes)."""
    root = root or t.ROOT
    themes = bundled(root)
    files = {"themes.css": stylesheet(themes), "themes.ts": registry(themes)}
    if out:
        out.mkdir(parents=True, exist_ok=True)
        for name, text in files.items():
            (out / name).write_text(text)
        (root / "_schema/tokens.schema.json").write_text(token_schema(themes[0]))
        (root / "_schema/theme.schema.json").write_text(manifest_schema())
    return files
