"""Millennium Skin's pieces: Nox as a clear Bondi keychain egg with an LCD face, the room marks as
chunky skin icons, gel transport keys, Y2K medals and five avatars. Writes themes/y2k/sprites.json
atomically, and a preview sheet with --preview <png> (both schemes' colours, approximated).

Letters (color.sprite.*): k outline, n dark, l mid-dark, L mid, m mist (chrome), C light-dim (the
glint: near-white in both skins), c light (white by night, navy ink by day: used for ink only),
e/E/r accent (amber gel by night, aqua by day), v/V/w familiar (Bondi plastic), g good (LCD green),
p alert (strawberry), P paper (LCD glass, dark in both), i ink (lit LCD segments)."""

import json
import os
import sys
from pathlib import Path

THEME = Path(__file__).resolve().parents[4] / "themes" / "y2k"

PALETTE = {
    "k": "outline", "n": "dark", "l": "mid-dark", "L": "mid", "m": "mist", "c": "light",
    "C": "light-dim", "e": "accent", "E": "accent-hi", "r": "accent-deep", "v": "familiar",
    "V": "familiar-mid", "w": "familiar-deep", "g": "good", "p": "alert", "P": "paper", "i": "ink",
}  # fmt: skip

# The Nox egg (the hero's keychain egg): a chrome keyring and eyelet on top, a clear Bondi shell
# widest low down, a lit rim top-left (C), speckles, a dark-green LCD window with lime eyes, three
# chrome keys.
EGG_TOP = [
    "........kkkk....",
    ".......kL..Lk...",
    "........kmLk....",
    "......kkkk......",
    "....kkCvvVkk....",
    "...kCCvCvvvVk...",
    "..kCkkkkkkkkVk..",
]
EGG_BOTTOM = [
    "..kCkkkkkkkkVk..",
    "..kvvmvmvmvVwk..",
    "...kvvCvvvVwk...",
    "....kkVVVVkk....",
    "......kkkk......",
]


def egg(face, left=".", right="."):
    """Nox with a 6 x 4 LCD face (rows of P, i or p)."""
    assert len(face) == 4 and all(len(r) == 6 for r in face), face
    return EGG_TOP + [f"{left}.kCk{row}kVk.{right}" for row in face] + EGG_BOTTOM


GLYPHS = {
    # ---------------------------------------------------------------- Nox
    "nox.idle": egg(["PPPPPP", "PiPPiP", "PPPPPP", "PPiiPP"]),
    "nox.blink": egg(["PPPPPP", "iiPPii", "PPPPPP", "PPiiPP"]),
    "nox.listening": egg(["PiPPiP", "PiPPiP", "PPPPPP", "PPiiPP"], left="g", right="g"),
    "nox.thinking": egg(["PPiPPi", "PPPPPP", "PPPPPP", "PPPiiP"]),
    "nox.happy": egg(["PiPPiP", "iPiiPi", "iPPPPi", "PiiiiP"]),
    "nox.error": egg(["pPppPp", "PpPPpP", "pPppPp", "PppppP"]),
    # ---------------------------------------------------------------- room marks
    "room.home": [
        "................",
        ".......kk.......",
        "......kEEk......",
        ".....kEEeek.....",
        "....kEEeeeek....",
        "...kEeeeeeerk...",
        "..kEeeeeeeerrk..",
        ".kkkkkkkkkkkkkk.",
        "..kmmmmmmmmmLk..",
        "..kmCmmkkkkmLk..",
        "..kmmmmkPPkmLk..",
        "..kmkkmkPPkmLk..",
        "..kmkgmkPgkmLk..",
        "..kmkkmkPPkmLk..",
        "..kLLLLkPPkLlk..",
        "..kkkkkkkkkkkk..",
    ],
    "room.listen": [  # a disc: silver, a rainbow sheen across it, a clear hub
        "................",
        ".....kkkkkk.....",
        "...kkCmmmmLkk...",
        "..kCmmmmmLLLLk..",
        "..kmmmEEmLLLlk..",
        ".kmmmEEggvLLllk.",
        ".kmmEEgkkkvLllk.",
        ".kmmEgk..kvvllk.",
        ".kmmEgk..kvpllk.",
        ".kmmmgkk.kppllk.",
        ".kLmmmvkkkplnnk.",
        ".kLLmmmvvpplnnk.",
        "..kLLmmmmllnnk..",
        "..kLLLllllnnnk..",
        "...kkLllllnkk...",
        ".....kkkkkk.....",
    ],
    "room.watch": [  # a clear Bondi CRT, antennas, an LCD-green picture
        "...k.......k....",
        "....k.....k.....",
        ".....k...k......",
        "......kkk.......",
        ".kkkkkkkkkkkkkk.",
        ".kCvvvvvvvvvvVk.",
        ".kvkkkkkkkkkVVk.",
        ".kvkPPPPPPPkVVk.",
        ".kvkPgPPPPPkVVk.",
        ".kvkPPPPPPPkVVk.",
        ".kvkPPPPPgPkVVk.",
        ".kvkkkkkkkkkVwk.",
        ".kVVVVVVVmVmVwk.",
        ".kkkkkkkkkkkkkk.",
        "...kwk....kwk...",
        "...kkk....kkk...",
    ],
    "room.house": [  # a clipboard list: chrome clip, lit ticks
        "......kkkk......",
        "..kkkkmCCmkkkk..",
        "..kLLkkkkkkLLk..",
        "..kLCCCCCCCCLk..",
        "..kLCgCnnnnCLk..",
        "..kLCggCCCCCLk..",
        "..kLCCCCCCCCLk..",
        "..kLCgCnnnnCLk..",
        "..kLCggCCCCCLk..",
        "..kLCCCCCCCCLk..",
        "..kLCnCnnnnCLk..",
        "..kLCCCCCCCCLk..",
        "..kLCnCnnCCCLk..",
        "..kLCCCCCCCCLk..",
        "..klLLLLLLLLlk..",
        "..kkkkkkkkkkkk..",
    ],
    "room.files": [  # a floppy: Bondi shell, chrome shutter, a label strip
        "................",
        ".kkkkkkkkkkkkk..",
        ".kvkmmmmmmmkVk..",
        ".kvkmmkkmmmkVVk.",
        ".kvkmmkkmmmkVVk.",
        ".kvkmmkkmmmkVVk.",
        ".kvkkkkkkkkkVVk.",
        ".kvvvvvvvvvvVVk.",
        ".kvkkkkkkkkkkVk.",
        ".kvkCCCCCCCCkVk.",
        ".kvkCnnnnnnCkVk.",
        ".kvkCCCCCCCCkVk.",
        ".kvkCnnnnCCCkVk.",
        ".kvkCCCCCCCCkwk.",
        ".kVVVVVVVVVVVwk.",
        ".kkkkkkkkkkkkkk.",
    ],
    "room.smart-home": [  # a gel light bulb on a chrome screw base
        "................",
        ".....kkkkkk.....",
        "....kEEEEeek....",
        "...kECCEeeerk...",
        "..kECEEeeeeerk..",
        "..kEEEeeeeeerk..",
        "..kEEeeeeeeerk..",
        "..keeeeeeeerrk..",
        "...keeeeeerrk...",
        "....kereerrk....",
        ".....kkkkkk.....",
        ".....kmmmLk.....",
        ".....kllllk.....",
        ".....kmmmLk.....",
        "......kllk......",
        ".......kk.......",
    ],
    "room.games": [  # a clear controller: grape shell, a chrome pad, gel buttons
        "................",
        "................",
        "...kkkk..kkkk...",
        "..kvvvvkkvvvVk..",
        ".kvCvvvvvvvvvVk.",
        ".kvvkkvvvvvpvVk.",
        "kvvkmmkvvvpvgVVk",
        "kvkmmmmkvvvgvVVk",
        "kvvkmmkvvvvvvVVk",
        "kvvvkkvvvvvvvVVk",
        "kvvvvvVkkkVVVVwk",
        ".kVVVVk...kVVwk.",
        "..kkkk.....kkk..",
        "................",
        "................",
        "................",
    ],
    "room.more": [  # three chrome beads in a row
        "................",
        "................",
        "................",
        "................",
        "................",
        "..kkk..kkk..kkk.",
        ".kCmLkkCmLkkCmLk",
        ".kmmlkkmmlkkmmlk",
        ".kLlnkkLlnkkLlnk",
        "..kkk..kkk..kkk.",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    "room.me": [  # a gel buddy: round head, shoulders, lit rim
        "................",
        "......kkkk......",
        ".....kEEeek.....",
        "....kECEeeek....",
        "....kEEeeerk....",
        "....keeeeerk....",
        ".....keeerk.....",
        "......kkkk......",
        "....kkvvvVkk....",
        "...kvCvvvvVVk...",
        "..kvCvvvvvvVVk..",
        "..kvvvvvvvvVwk..",
        "..kvvvvvvvVVwk..",
        "..kVVVVVVVVwwk..",
        "..kkkkkkkkkkkk..",
        "................",
    ],
    # ---------------------------------------------------------------- transport (gel keys, 9 x 9)
    "transport.play": [
        ".kk......",
        ".kEk.....",
        ".kEek....",
        ".kEeek...",
        ".kEeeek..",
        ".keeerk..",
        ".keerk...",
        ".kerk....",
        ".kkk.....",
    ],
    "transport.pause": [
        "kkkk.kkkk",
        "kEek.kEek",
        "kEek.kEek",
        "kEek.kEek",
        "kEek.kEek",
        "keek.keek",
        "keek.keek",
        "kerk.kerk",
        "kkkk.kkkk",
    ],
    "transport.next": [
        "kk....kkk",
        "kEk...kEk",
        "kEek..kEk",
        "kEeek.kEk",
        "kEeeekkek",
        "keeerkkek",
        "keerk.kek",
        "kerk..krk",
        "kkk...kkk",
    ],
    "transport.previous": [
        "kkk....kk",
        "kEk...kEk",
        "kEk..kEek",
        "kEk.kEeek",
        "kekkEeeek",
        "kekkeeerk",
        "kek.keerk",
        "krk..kerk",
        "kkk...kkk",
    ],
    "transport.stop": [
        ".........",
        ".kkkkkkk.",
        ".kEEEEek.",
        ".kEeeeek.",
        ".kEeeeek.",
        ".kEeeeek.",
        ".keeeerk.",
        ".kkkkkkk.",
        ".........",
    ],
    # ---------------------------------------------------------------- avatars (16 x 16 fills the ring)
    "avatar.moon": [
        "................",
        ".....kkkk.......",
        "...kkmmCCk......",
        "..kmmCCkk.......",
        "..kmCCk.....k...",
        ".kmmCk.....kEk..",
        ".kmmCk....kEEEk.",
        ".kmmCk.....kEk..",
        ".kLmmk......k...",
        ".kLmmmk.........",
        "..kLmmmk....kk..",
        "..kLLmmmkkkkmk..",
        "...klLLmmmmmLk..",
        "....kklLLLLlk...",
        "......kkkkkk....",
        "................",
    ],
    "avatar.bat": [
        "................",
        "................",
        "..k..........k..",
        "..kk...kk...kk..",
        "..knk.kllk.knk..",
        ".knlnkllllknlnk.",
        ".knllkpllpkllnk.",
        "knlmllllllllmlnk",
        "knmlnllCCllnlmnk",
        "knlk.klllllk.klk",
        "kk...kllllk...kk",
        "......kllk......",
        ".......kk.......",
        ".......kk.......",
        "......kLLk......",
        ".......kk.......",
    ],
    "avatar.raven": [
        "................",
        ".....kkkk.......",
        "....knllnk......",
        "...knlCknnk.....",
        "..keknllnnk.....",
        ".keekknnnnnk....",
        "..kkknnnnnnnk...",
        "....knnllnnnnk..",
        "...knnlllnnnnnk.",
        "...knlllnnnnnnk.",
        "....knnnnnnnnk..",
        ".....knnnnnkk...",
        "......kkkkknk...",
        ".......kekkek...",
        "......keek.kek..",
        ".......kk...k...",
    ],
    "avatar.rose": [
        "................",
        ".....kkkkk......",
        "....kppCppk.....",
        "...kpCpppppk....",
        "..kpppkkkpppk...",
        "..kppkpppkppk...",
        "..kppkpkppkpk...",
        "..kpppkkppppk...",
        "...kpppppppk....",
        "....kkpppkk.....",
        "......kgk.......",
        "...kk.kgk.......",
        "..kggkkgk.......",
        "...kkgggk.kk....",
        "......kgkkggk...",
        "......kgk.kk....",
    ],
    "avatar.ghost": [
        "................",
        ".....kkkkkk.....",
        "....kCCmmmmk....",
        "...kCmmmmmmLk...",
        "..kCmmmmmmmmLk..",
        "..kmmkkmmkkmLk..",
        "..kmmkkmmkkmLk..",
        "..kmmmmmmmmmLk..",
        "..kmpmmkkmmpLk..",
        "..kmmmmmmmmmLk..",
        "..kmmmmmmmmLLk..",
        "..kmmmmmmmLLLk..",
        "..kLmmLLmLLLlk..",
        "..kLkkLLkLLklk..",
        "..kk..kk.kk.kk..",
        "................",
    ],
    # ---------------------------------------------------------------- medals (16 x 16)
    "title.dj": [  # headphones: a chrome band, gel cups
        "................",
        ".....kkkkkk.....",
        "...kkmmCCmmkk...",
        "..kmmkkkkkkmLk..",
        ".kmLk......kLlk.",
        ".kmk........klk.",
        ".kmk........klk.",
        "kkkkk......kkkkk",
        "kEEek......kEEek",
        "kEeek......keeek",
        "kEeek......keerk",
        "keeek......keerk",
        "kerrk......krrrk",
        "kkkkk......kkkkk",
        "................",
        "................",
    ],
    "title.explorer": [  # a Bondi globe with a chrome orbit
        "................",
        "......kkkk......",
        "....kkCvvvkk....",
        "...kCvvggvvVk...",
        "..kCvgggvvvVVk..",
        "kkkkkkggvvvVkkkk",
        "kmmmmkkkvvkkLLlk",
        ".kkkvvvkkkkvVkk.",
        "..kvvvvvggvVVk..",
        "..kvvvvgggVVwk..",
        "...kvvvvgVVwk...",
        "....kkVVVwkk....",
        "......kkkk......",
        "................",
        "................",
        "................",
    ],
    "title.night_owl": [  # a chrome crescent and a sparkle
        "................",
        "......kkkk......",
        "....kkmCCk......",
        "...kmCCkk...k...",
        "..kmCCk....kEk..",
        "..kmCk....kEEEk.",
        ".kmmCk...kEEEEEk",
        ".kmmCk....kEEEk.",
        ".kLmmk.....kEk..",
        ".kLmmmk.....k...",
        "..kLmmmk....kk..",
        "..kLLmmmkkkkmk..",
        "...klLLmmmmmLk..",
        "....kklLLLLlk...",
        "......kkkkkk....",
        "................",
    ],
    "title.early_bird": [  # a gel sun rising over a chrome horizon, rays out
        "................",
        "k......kk......k",
        ".k.....EE.....k.",
        "..k..........k..",
        "......kkkk......",
        "....kkEEEekk....",
        "...kEECEeeeek...",
        "kk.kEEEeeeerk.kk",
        "..kEEeeeeeeerk..",
        "..kEeeeeeeeerk..",
        "kkkkkkkkkkkkkkkk",
        "kCCmmmmmmmmmmLLk",
        "kkkkkkkkkkkkkkkk",
        "..kLLLLLLLLLLk..",
        "...kkkkkkkkkk...",
        "................",
    ],
    "title.weekend": [  # tinted shades with a glint
        "................",
        "................",
        "................",
        "................",
        "kkkkkkkkkkkkkkkk",
        "kmkkkkkkkkkkkkmk",
        "kkCvvvvkkvvvvVkk",
        ".kvCvvVkkvCvVVk.",
        ".kvvvVVk.kvvVVk.",
        ".kvvVVwk.kvVVwk.",
        "..kVVwk...kVwk..",
        "...kkk.....kk...",
        "................",
        "................",
        "................",
        "................",
    ],
    "title.genre_guardian": [  # a chrome shield with a gel note
        "................",
        ".kkkkkkkkkkkkkk.",
        ".kCmmmmmmmmmmLk.",
        ".kmmmmmkkkkmLLk.",
        ".kmmmmmkEEkmLLk.",
        ".kmmmmmkEkkmLLk.",
        ".kmmmmmkEkmmLLk.",
        ".kmmmkkkEkmmLlk.",
        ".kmmkEEeekmLLlk.",
        "..kmkEeeekmLlk..",
        "..kmmkkkkmLLlk..",
        "...kmmmmmLLlk...",
        "....kmmmLLlk....",
        ".....kmLLlk.....",
        "......kllk......",
        ".......kk.......",
    ],
    "title.broken_record": [  # a disc with a zig-zag crack
        "................",
        ".....kkkkkk.....",
        "...kkCmmkLLkk...",
        "..kCmmmmmkLLLk..",
        "..kmmmEEmkkLlk..",
        ".kmmmEEggvkLllk.",
        ".kmmEEgkkkkLllk.",
        ".kmmEgk..kkvllk.",
        ".kmmEgkk.kvpllk.",
        ".kmmmgkkkkppllk.",
        ".kLmmmvkkkplnnk.",
        ".kLLmmmvkpplnnk.",
        "..kLLmmmkkllnk..",
        "..kLLLllkllnnk..",
        "...kkLllkknkk...",
        ".....kkkkkk.....",
    ],
    "title.marathon": [  # a stopwatch: chrome case, Bondi face
        "......kkkk......",
        "......kmLk......",
        ".......kk.......",
        ".....kkkkkk.....",
        "...kkvvvvvvkk...",
        "..kCvvvvvvvvVk..",
        "..kvvvvkvvvvVk..",
        ".kvvvvvkvvvvVVk.",
        ".kvvvvvkvvvvVVk.",
        ".kvvvvvkkkkvVVk.",
        ".kvvvvvvvvvvVVk.",
        "..kvvvvvvvvVVk..",
        "..kVvvvvvvVVwk..",
        "...kkVVVVVwkk...",
        ".....kkkkkk.....",
        "................",
    ],
    "title.radio_host": [  # a chrome ball microphone on a gel handle
        "................",
        ".....kkkkk......",
        "....kCmkmLk.....",
        "...kCmkmkmLk....",
        "...kmkmkmkLk....",
        "...kmmkmkLlk....",
        "....kLkLkLk.....",
        ".....kkkkk......",
        "......kEk.......",
        "......kek.......",
        "......kek.......",
        "......kek.......",
        "......krk.......",
        ".....kkkkk......",
        "....kLLLLLk.....",
        ".....kkkkk......",
    ],
    "title.task_hero": [  # a gel star badge with a lit tick
        ".......kk.......",
        "......kEEk......",
        "......kEEk......",
        ".kkkkkkEekkkkkk.",
        ".kEEEEEeeeeeerk.",
        "..kEEeeeeeegerk.",
        "...kEeeeeeggrk..",
        "....kegeeggrk...",
        "....keggggerk...",
        "...kEeeggeeerk..",
        "...kEeerkkeerk..",
        "..kEeerk..kerrk.",
        "..kEerk....krrk.",
        ".kEerk......krk.",
        ".kkkk........kk.",
        "................",
    ],
    "title.grocery_runner": [  # a clear shopping bag with a leaf
        "................",
        "......kkkk......",
        ".....kk..kk.....",
        ".....k....k.....",
        "...kkkkkkkkkk...",
        "...kCvvvvvvVk...",
        "...kvvvvvkkVk...",
        "...kvvvvkggkk...",
        "...kvvvkggggk...",
        "...kvvvkgggkVk..",
        "...kvvvvkkkVVk..",
        "...kvvvvvvvVVk..",
        "...kvvvvvvVVwk..",
        "...kVVVVVVVwwk..",
        "...kkkkkkkkkkk..",
        "................",
    ],
    "title.planner": [  # a Bondi PDA with an LCD grid
        "................",
        "...kkkkkkkkkk...",
        "..kCvvvvvvvvVk..",
        "..kvkkkkkkkkVk..",
        "..kvkPiPiPiPkk..",
        "..kvkPPPPPPPkk..",
        "..kvkPiPgPiPkk..",
        "..kvkPPPPPPPkk..",
        "..kvkPiPiPiPkk..",
        "..kvkkkkkkkkVk..",
        "..kvvvvvvvvvVk..",
        "..kvvmkvvkmvVk..",
        "..kvmmmkkmmmVk..",
        "..kVVmVVVVmVwk..",
        "...kkkkkkkkkk...",
        "................",
    ],
    "title.wall_poet": [  # a sticky note and a gel pen
        "................",
        "..kkkkkkkkkk....",
        "..kEEEEEEEEk....",
        "..kEnnnnnnEk....",
        "..kEEEEEEEEk.kk.",
        "..kEnnnnnEEkkvk.",
        "..kEEEEEEEEkvvk.",
        "..kEnnnnEEEkvk..",
        "..kEEEEEEEkvvk..",
        "..kEnnnEEEkvk...",
        "..kEEEEEEkvvk...",
        "..kEEEEEEkmk....",
        "..keeeeeekk.....",
        "..kkkkkkkk......",
        "................",
        "................",
    ],
    "title.courier": [  # an envelope sealed with a gel heart
        "................",
        "................",
        "................",
        ".kkkkkkkkkkkkkk.",
        ".kkCmmmmmmmmLkk.",
        ".kmkkmmmmmmkkLk.",
        ".kmmmkkmmkkmmLk.",
        ".kmmmmkppkmmmLk.",
        ".kmmmkppppkmmLk.",
        ".kmmkkppppkkmLk.",
        ".kmkmmkppkmmkLk.",
        ".kkmmmmkkmmmmkk.",
        ".kLLLLLLLLLLLlk.",
        ".kkkkkkkkkkkkkk.",
        "................",
        "................",
    ],
    "title.curator": [  # a chrome frame around a sparkle
        "................",
        ".kkkkkkkkkkkkkk.",
        ".kCmmmmmmmmmmLk.",
        ".kmkkkkkkkkkkLk.",
        ".kmkPPPPkPPPkLk.",
        ".kmkPPPkEkPPkLk.",
        ".kmkPPkEEEkPkLk.",
        ".kmkPkEEEEEkkLk.",
        ".kmkPPkEEEkPkLk.",
        ".kmkPPPkEkPPkLk.",
        ".kmkPPPPkPPPkLk.",
        ".kmkkkkkkkkkklk.",
        ".kLLLLLLLLLLllk.",
        ".kkkkkkkkkkkkkk.",
        "................",
        "................",
    ],
    "title.high_scorer": [  # a gel trophy
        "................",
        ".kkkkkkkkkkkkkk.",
        "kkEEEEEeeeeeerkk",
        "kEkEEeeeeeeerkrk",
        "kEkEEeeeeeeerkrk",
        ".kkEeeeeeeeerkk.",
        "...kEeeeeeerk...",
        "....kEeeeerk....",
        ".....keeerk.....",
        "......kerk......",
        "......kerk......",
        ".....kkkkkk.....",
        "....kmmmmmLk....",
        "...kCmmmmmLLk...",
        "...kkkkkkkkkk...",
        "................",
    ],
    "title.collector": [  # a heart gem with facets
        "................",
        "................",
        "..kkkk....kkkk..",
        ".kpCCpk..kppppk.",
        "kpCppppkkpppppnk",
        "kpCpppppppppppnk",
        "kppppppppppppnnk",
        "kpppppppppppppnk",
        ".kpppppppppppnk.",
        "..kpppppppppnk..",
        "...kpppppppnk...",
        "....kpppppnk....",
        ".....kpppnk.....",
        "......kpnk......",
        ".......kk.......",
        "................",
    ],
    "title.game_hopper": [  # a joystick: gel ball, chrome shaft, Bondi base
        "................",
        "......kkkk......",
        ".....kECeek.....",
        ".....kEeerk.....",
        ".....keerrk.....",
        "......kkkk......",
        ".......mk.......",
        ".......mk.......",
        ".......mk.......",
        "..kkkkkkkkkkkk..",
        ".kCvvvvvvvvvpVk.",
        ".kvvvvvvvvvvvVk.",
        ".kvvvvvvvvvVVwk.",
        ".kkkkkkkkkkkkkk.",
        "................",
        "................",
    ],
    "title.console_hopper": [  # a clear handheld: LCD screen, pad, two keys
        "...kkkkkkkkkk...",
        "..kCvvvvvvvvVk..",
        "..kvkkkkkkkkVk..",
        "..kvkPPPPPPkVk..",
        "..kvkPgPPPPkVk..",
        "..kvkPPPPgPkVk..",
        "..kvkPPPPPPkVk..",
        "..kvkkkkkkkkVk..",
        "..kvvvvvvvvvVk..",
        "..kvkkvvvvvpVk..",
        "..kkmmkvvvpvVk..",
        "..kvkkvvvvvvVk..",
        "..kvvvvvnvnvVk..",
        "..kvvvvvvvvVwk..",
        "...kkkkkkkkkk...",
        "................",
    ],
    "title.romhacker": [  # a chip: chrome pins, a black body, a lit LED
        "................",
        "....k.k.k.k.....",
        "....m.m.m.m.....",
        "..kkkkkkkkkkk...",
        "kmknnnnnnnnnkmk.",
        "..knlllllllnk...",
        "kmknlnnnnnlnkmk.",
        "..knlnPPPnlnk...",
        "kmknlnPgPnlnkmk.",
        "..knlnPPPnlnk...",
        "kmknlllllllnkmk.",
        "..knnnnnnnnnk...",
        "..kkkkkkkkkkk...",
        "....m.m.m.m.....",
        "....k.k.k.k.....",
        "................",
    ],
}


def check():
    bad = []
    for name, rows in GLYPHS.items():
        w = len(rows[0])
        for i, row in enumerate(rows):
            if len(row) != w:
                bad.append(f"{name} row {i}: {len(row)} != {w}")
            for ch in row:
                if ch != "." and ch not in PALETTE:
                    bad.append(f"{name} row {i}: letter {ch!r}")
        if w > 16 or len(rows) > 16:
            bad.append(f"{name}: larger than 16")
    if bad:
        raise SystemExit("\n".join(bad))


def write():
    data = {
        "$description": "Millennium Skin: Nox as a clear Bondi keychain egg with an LCD face, chunky skin room marks, gel transport keys, Y2K medals and avatars. Drawn by code (docs/design/themes/y2k/sprites_src.py), CC-BY-4.0.",
        "palette": PALETTE,
        "glyphs": GLYPHS,
    }
    path = THEME / "sprites.json"
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(data, indent=1, ensure_ascii=False) + "\n")
    os.replace(tmp, path)


# Approximate colours for the preview sheet only (the app paints from the tokens).
PREVIEW = {
    "dark": {"bg": "#10142a", "k": "#0a0c1c", "n": "#373c52", "l": "#686f89", "L": "#9aa2ba", "m": "#c9cfe0", "c": "#f6f8ff",
             "C": "#dde8f5", "e": "#ffad33", "E": "#ffe19a", "r": "#c5601a", "v": "#34c4d8", "V": "#2a8fad", "w": "#1c5d7a",
             "g": "#8dff6a", "p": "#ff5a6e", "P": "#0f2420", "i": "#a4ff7a"},
    "light": {"bg": "#e3dbf7", "k": "#252f59", "n": "#5f6a88", "l": "#8c96b3", "L": "#b5bdd5", "m": "#dce1ee", "c": "#262f5a",
              "C": "#f0f6ff", "e": "#1f84a3", "E": "#b3ecf6", "r": "#0f6480", "v": "#3cb4d6", "V": "#1b8aad", "w": "#0e5d80",
              "g": "#4fb040", "p": "#e23a5a", "P": "#1d3a40", "i": "#a4ff7a"},
}  # fmt: skip


def preview(out):
    from PIL import Image, ImageDraw

    names = list(GLYPHS)
    cell, z = 72, 4
    cols = 8
    rows = (len(names) + cols - 1) // cols
    sheet = Image.new("RGB", (cols * cell * 2 + 8, rows * cell), "#222")
    for s, scheme in enumerate(PREVIEW):
        pal = PREVIEW[scheme]
        for n, name in enumerate(names):
            x0 = s * (cols * cell + 8) + (n % cols) * cell
            y0 = (n // cols) * cell
            d = ImageDraw.Draw(sheet)
            d.rectangle([x0, y0, x0 + cell - 2, y0 + cell - 2], fill=pal["bg"])
            g = GLYPHS[name]
            ox = x0 + (cell - len(g[0]) * z) // 2
            oy = y0 + (cell - len(g) * z) // 2
            for y, row in enumerate(g):
                for x, ch in enumerate(row):
                    if ch != ".":
                        d.rectangle([ox + x * z, oy + y * z, ox + x * z + z - 1, oy + y * z + z - 1], fill=pal[ch])
    pass
    sheet.save(out)


if __name__ == "__main__":
    check()
    write()
    if "--preview" in sys.argv:
        preview(sys.argv[sys.argv.index("--preview") + 1])
    print("sprites.json written:", len(GLYPHS), "pieces")
