#!/usr/bin/env python3
"""Writes docs/CODE-INDEX.md: every backend module with its functions, classes and HTTP
routes (with line links), the frontend files and their exports, and the migrations.

    python3 tools/code_index.py [ROOT]      # ROOT defaults to this repository

Run it after changing code so agents and people find things from an index that matches the
source. Standard library only."""

import ast
import re
import sys
from pathlib import Path

HTTP = {"get", "post", "patch", "put", "delete"}


def backend(root):
    lines = []
    for path in sorted((root / "backend/houseos").glob("*.py")):
        tree, rel = ast.parse(path.read_text()), path.relative_to(root).as_posix()
        lines += [f"## {path.stem}", "", f"Source: [{rel}](../{rel})", ""]
        if doc := ast.get_docstring(tree):
            lines += [doc, ""]
        for node in tree.body:
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                continue
            is_class = isinstance(node, ast.ClassDef)
            signature = f"class {node.name}" if is_class else f"{node.name}({ast.unparse(node.args)})"
            lines.append(f"- [`{signature}`](../{rel}#L{node.lineno})")
            if doc := ast.get_docstring(node):
                lines.append("  " + doc.splitlines()[0])
            for decorator in node.decorator_list:
                call = decorator.func if isinstance(decorator, ast.Call) else None
                if isinstance(call, ast.Attribute) and call.attr in HTTP:
                    lines.append(f"  HTTP: `{ast.unparse(decorator)}`")
            if is_class:
                for child in node.body:
                    if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                        lines.append(f"  Method: `{child.name}({ast.unparse(child.args)})`")
        lines.append("")
    return lines


def frontend(root):
    lines = ["# Frontend files and exports", ""]
    export = re.compile(r"export\s+(?:default\s+)?(?:async\s+)?(?:function|class|const|type|interface)\s+(\w+)")
    for path in sorted((root / "frontend/src").glob("*")):
        if path.suffix in {".ts", ".tsx", ".css"}:
            names = export.findall(path.read_text())
            rel = path.relative_to(root).as_posix()
            lines.append(f"- [{path.name}](../{rel}): " + (", ".join(f"`{n}`" for n in names) or "styles"))
    return lines


def migrations(root):
    lines = ["", "# Migrations", ""]
    for path in sorted((root / "backend/migrations/versions").glob("*.py")):
        doc = (ast.get_docstring(ast.parse(path.read_text())) or "").split("\n")[0]
        lines.append(f"- [{path.name}](../{path.relative_to(root).as_posix()}): {doc}")
    return lines


def main():
    root = Path(sys.argv[1] if len(sys.argv) > 1 else Path(__file__).resolve().parents[1])
    lines = [
        "# Code index",
        "",
        "Generated by `tools/code_index.py` from the source; regenerate it after code changes. "
        "Read docs/ARCHITECTURE.md first and use this index to find things. Route paths are "
        "relative to each module's router; main.py mounts them below /api/v1.",
        "",
        *backend(root),
        *frontend(root),
        *migrations(root),
    ]
    (root / "docs").mkdir(exist_ok=True)
    (root / "docs/CODE-INDEX.md").write_text("\n".join(lines) + "\n")
    print(f"docs/CODE-INDEX.md: {len(lines)} lines")


if __name__ == "__main__":
    main()
