"""Legacy's pixel pieces: Nox the black cat, the five avatars, the room marks and the 20 medals,
hand-placed pixel by pixel. Writes themes/carved-night/sprites.json (atomically) and a preview.

    python3 docs/design/themes/carved-night/pieces.py [preview.png]

Letters are color.sprite tokens (the file's palette), so the theme's colours paint them:
k outline · n dark · l mid-dark · L mid · m mist · c light · C light-dim · e candle · E candle-hi
r ember · v/V/w lilac · g gas green · p rose · P paper · i ink.
"""

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
OUT = ROOT / "themes/carved-night/sprites.json"

PALETTE = {"k": "outline", "n": "dark", "l": "mid-dark", "L": "mid", "m": "mist", "c": "light", "C": "light-dim",
           "e": "accent", "E": "accent-hi", "r": "accent-deep", "v": "familiar", "V": "familiar-mid",
           "w": "familiar-deep", "g": "good", "p": "alert", "P": "paper", "i": "ink"}  # fmt: skip

# ---------------------------------------------------------------- Nox, the house's black cat
# Moonlit from the upper left: a mid-dark rim on the left of the head and ears, green eyes.
NOX_HEAD = [
    "................",
    "..k.........k...",
    ".klk.......kLk..",
    ".kLlk.....kLlk..",
    ".klnnkkkkknnlk..",
    "kLnnnnnnnnnnnk..",
    "kLnggnnnnnggnk..",
    "klnggknnnkggnk..",
    "klnnnnnpnnnnnk..",
    ".klnnnknknnnk...",
    "..kknnnnnnnkk...",
]
NOX_BODY = [
    "..klnnnnnnnk..k.",
    ".klnnnnnnnnnk.lk",
    ".klnnnnnnnnnkkLk",
    ".klnnlnnnlnnnnk.",
    "..kkkkkkkkkkkk..",
]


def nox(head_edit=None, body=NOX_BODY):
    head = list(NOX_HEAD)
    for row, text in (head_edit or {}).items():
        head[row] = text
    return head + body


NOX = {
    "nox.idle": nox(),
    "nox.blink": nox({6: "kLnnnnnnnnnnnk..", 7: "klnkkknnnkkknk.."}),
    # listening: ears up and turned, eyes wide and round, looking at you
    "nox.listening": nox({
        0: "..k.........k...",
        1: ".klk.......klk..",
        2: ".kLlk.....kLlk..",
        3: ".kLnlk...klnlk..",
        6: "kLngggnnngggnk..",
        7: "klngkgnnngkgnk..",
    }),
    # thinking: eyes up to the side, a paw raised to the chin
    "nox.thinking": nox({0: "..............m.", 1: "..k.........k.m.", 2: ".klk.......kLk..",
                         6: "kLnkgnnnnnkgnk..", 7: "klnggnnnnnggnk..", 9: ".klnnnkkknnnk...",
                         10: "..kknnnnnlLkk..."},
                        [".klnnnnnnkLLk.k.", ".klnnnnnnnkk.klk", ".klnnnnnnnnnkkLk", ".klnnlnnnlnnnnk.",
                         "..kkkkkkkkkkkk.."]),
    # happy: eyes shut in arcs, mouth open, the tail up
    "nox.happy": nox({6: "kLnnknnnnnknnk..", 7: "klnkgknnnkgknk..", 8: "klpnnnnpnnnnpk..",
                      9: ".klnnkpppknnk...", 0: ".............k..", 1: "..k.........kLk."},
                     ["..klnnnnnnnk.kLk", ".klnnnnnnnnnkkk.", ".klnnnnnnnnnk...", ".klnnlnnnlnnnk..",
                      "..kkkkkkkkkkkk.."]),
    # error: ears flat, small startled pupils, a drop of sweat
    "nox.error": nox({1: "................", 2: "................", 3: "kkLk.......kLkk.",
                      4: "klLnkkkkkkknLlk.", 6: "kLnccnnnnnccnk.m", 7: "klnckknnnkckmk.m",
                      9: ".klnnnkkknnnk..."}),
}

# ---------------------------------------------------------------- avatars (fill their ring)
AVATARS = {
    "avatar.moon": [
        "................",
        "......kkkk......",
        "....kkcCCck.....",
        "...kcCCkk.......",
        "..kcCCk.........",
        "..kcCk......e...",
        ".kcCCk.....eEe..",
        ".kcCCk......e...",
        ".kcCCk..........",
        ".kcCCCk.........",
        "..kcCCCk.....k..",
        "..kccCCCkkkkkCk.",
        "...kccCCCCCCCk..",
        "....kkcccccCk...",
        "......kkkkkk....",
        "................",
    ],
    "avatar.bat": [
        "................",
        "................",
        ".....k....k.....",
        ".....kk..kk.....",
        "k....klkklk....k",
        "kk..klnnnnlk..kk",
        "klk.kneknenk.klk",
        "klnkknnnnnnkknlk",
        "klnnlnnnnnnlnnlk",
        "klnnnlnccnlnnnlk",
        ".knnnnlnnlnnnnk.",
        ".kn.knnnnnnk.nk.",
        "..k..knnnnk..k..",
        "......knnk......",
        ".......kk.......",
        "................",
    ],
    "avatar.raven": [
        "................",
        "......kkkk......",
        ".....klllnk.....",
        "....klLlnnnk....",
        "..kkklenknnk....",
        ".kmmLknnnnnk....",
        "..kkkknnnnnk....",
        ".....knnnnnnk...",
        "....klnnnnnnnk..",
        "...klLnlnnnnnk..",
        "...klnlnlnnnnnk.",
        "....klnlnnnnnnnk",
        ".....kknnnnnkkkk",
        ".......knkkk....",
        "......kmkmk.....",
        "................",
    ],
    "avatar.rose": [
        "................",
        ".....kkkkk......",
        "....kpppppk.....",
        "...kpprrpppk....",
        "..kpprpprrpk....",
        "..kprppkpprpk...",
        "..kprpkpppppk...",
        "..kpprppprppk...",
        "...kpprrrppk....",
        "....kkpppkk.....",
        "..kk...kg...kk..",
        ".kggk..kg..kggk.",
        "..kggkkgk.kggk..",
        "...kkk.kgkkkk...",
        ".......kg.......",
        "........k.......",
    ],
    "avatar.ghost": [
        "................",
        ".....kkkkk......",
        "....kcccccck....",
        "...kcccccccCk...",
        "..kccccccccCCk..",
        "..kcckccckcCCk..",
        "..kcckccckcCCk..",
        "..kpcccccccpCk..",
        "..kcccckkcccCk..",
        "..kccccccccCCk..",
        "..kccccccccCCk..",
        "..kcccccccCCCk..",
        "..kccCcccCCCmk..",
        "..kcCkCcCkCmmk..",
        "..kCk.kCk.kmk...",
        "...k...k...k....",
    ],
}

# ---------------------------------------------------------------- room marks
ROOMS = {
    # Home: the manor, its tower and a lit window
    "room.home": [
        "...k............",
        "..kLk...........",
        "..kmk.....k.....",
        ".kmLlk...kLk....",
        ".kLnlk..kmLlk...",
        "kmnnnlkkmLnnlk..",
        "kLnnnnkmLnnnnlk.",
        ".kncnkkLnnnnnnlk",
        ".knEnkkLnEnEnlk.",
        ".knnnkkLnEnEnnk.",
        ".kncnkkLnnnnnnk.",
        ".knEnkkLnnkkknk.",
        ".knnnkkLnnkEknk.",
        "kkkkkkkkkkkkkkkk",
        "................",
        "................",
    ],
    # Listen: the gramophone, its brass horn
    "room.listen": [
        "....kkkkkk......",
        "..kkeEEEEekk....",
        ".keEEkkkkEEek...",
        ".kEEknnnnkEek...",
        "keEknnnnnnkeek..",
        "keEknnnnnnkerk..",
        ".keEknnnnkerk...",
        ".kreekkkkerrk...",
        "..krreeeerrk....",
        "...kkrrrrkk.....",
        ".....kkek.......",
        "..kkkkkekkkkk...",
        ".kLLLLLLLLLLLk..",
        ".klrrrrrrrrrrk..",
        ".klrkrrrrrkrrk..",
        ".kkkkkkkkkkkkk..",
    ],
    # Watch: the carved cabinet television
    "room.watch": [
        "................",
        "......k...k.....",
        ".......k.k......",
        "..kkkkkkkkkkkk..",
        ".krrrrrrrrrrrrk.",
        ".krkkkkkkkkrrrk.",
        ".krkmmmLLkkrerk.",
        ".krkmLLLLLkrrrk.",
        ".krkLLLLLLkrerk.",
        ".krkLLLLlLkrrrk.",
        ".krkkLLLlkkrkrk.",
        ".krrkkkkkkrrkrk.",
        ".krrrrrrrrrrrrk.",
        "..kkkkkkkkkkkk..",
        "..kr........rk..",
        "..kk........kk..",
    ],
    # House: the kitchen cauldron, something green bubbling
    "room.house": [
        "................",
        ".......g........",
        ".....g....g.....",
        "......kgk.......",
        "...kkkkkkkkkk...",
        "..kgggggggggEk..",
        ".kkkkkkkkkkkkkk.",
        ".klLnnnnnnnnnnk.",
        "kLlnnnnnnnnnnnnk",
        "kLnnnnnnnnnnnnnk",
        "klnnnnnnnnnnnnnk",
        "klnnnnnnnnnnnnnk",
        ".klnnnnnnnnnnnk.",
        "..kknnnnnnnnkk..",
        "..krkkkkkkkkrk..",
        ".rrereerreerrer.",
    ],
    # Files: an old book, bound in leather, a ribbon marker
    "room.files": [
        "................",
        "..kkkkkkkkkkk...",
        ".krrrrrrrrrrrk..",
        ".kreeeeeeeeerk..",
        ".krerrrrrrrerk..",
        ".krerrrrrrrerk..",
        ".krerreeerrerk..",
        ".krerrrrrrrerk..",
        ".krerrrrrrrerk..",
        ".kreeeeeeeeerk..",
        ".krrrrrrrrrrrk..",
        ".kkPPPPPPPPPPkk.",
        "..kCPPPPPPPPPPk.",
        "...kkkkkkpkkkk..",
        ".........p......",
        ".........p......",
    ],
    # Smart home: a gas lamp, lit
    "room.smart-home": [
        "......kkk.......",
        ".....kLLLk......",
        "....kkkkkkk.....",
        "...kmEEEEEmk....",
        "...kmEEcEEmk....",
        "...kmeEEEemk....",
        "...kmeeeeemk....",
        "....kkkkkkk.....",
        ".....kLlk.......",
        "......kk........",
        "......kLk.......",
        "......klk.......",
        "......klk.......",
        "......klk.......",
        "....kkLlkkk.....",
        "...klllllllk....",
    ],
    # Games: the attic's spinning top
    "room.games": [
        "................",
        ".......kk.......",
        ".......klk......",
        "......kkLkk.....",
        "....kkeeEeekk...",
        "...kpppppppppk..",
        "..keeeeEeeeeeek.",
        "..kpppppppppppk.",
        "...keeeeeeeeek..",
        "....kpppppppk...",
        ".....keeeeek....",
        "......kpppk.....",
        ".......kek......",
        "........k.......",
        "....m......m....",
        "..mm........mm..",
    ],
    # More: a door to the rest of the house, arched, its knob lit
    "room.more": [
        ".....kkkkkk.....",
        "...kkrrrrrrkk...",
        "..krrrrkkrrrrk..",
        "..krrkrkkrkrrk..",
        ".krrkrrkkrrkrrk.",
        ".krkrrrkkrrrkrk.",
        ".krkrrrkkrrrkrk.",
        ".krkkkkkkkkkkrk.",
        ".krkrrrkkrrrkrk.",
        ".krkrrrkkreEkrk.",
        ".krkrrrkkrrrkrk.",
        ".krkrrrkkrrrkrk.",
        ".krkkkkkkkkkkrk.",
        ".krrrrrkkrrrrrk.",
        "kkkkkkkkkkkkkkkk",
        "kLLLLLLLLLLLLLLk",
    ],
    # Me: a hand mirror in a gilt frame
    "room.me": [
        ".....kkkkkk.....",
        "....keeEEeek....",
        "...kemmmmmmek...",
        "..kemcmmmmmmek..",
        "..kecmmmmmmmek..",
        "..kemmmmmmmLek..",
        "..kemmmmmmLLek..",
        "..kemmmmmLLLek..",
        "...kemmmLLLek...",
        "....keeeeeek....",
        ".....kkeekk.....",
        "......kerk......",
        "......kerk......",
        "......kerk......",
        "......kErk......",
        ".......kk.......",
    ],
}

# ---------------------------------------------------------------- medals: things of the manor
MEDALS = {
    "title.dj": [  # a record on the gramophone
        "................",
        ".....kkkkkk.....",
        "...kknnnnnnkk...",
        "..knnlnnnnnnnk..",
        "..knlnnnnnnnnk..",
        ".knlnnkkkknnnnk.",
        ".knnnkeeEekknnk.",
        ".knnnkerkeknnnk.",
        ".knnnkeeeeknnnk.",
        ".knnnnkkkknnnnk.",
        "..knnnnnnnnnlk..",
        "..knnnnnnnnlnk..",
        "...kknnnnnnkk...",
        ".....kkkkkk.....",
        "................",
        "................",
    ],
    "title.explorer": [  # a lantern
        "......kkk.......",
        ".....k...k......",
        ".....kkkkk......",
        "....kLlllLk.....",
        "...kkkkkkkkk....",
        "...kLkEEEkLk....",
        "...kLEEcEEkk....",
        "...kLEEcEElk....",
        "...kLeEEEelk....",
        "...kLeeeeelk....",
        "...kkkkkkkkk....",
        "....kLlllLk.....",
        ".....kkkkk......",
        "................",
        "................",
        "................",
    ],
    "title.night_owl": [  # an owl
        "................",
        "...k.......k....",
        "...kk.....kk....",
        "...klkkkkklk....",
        "..klnnnnnnnlk...",
        "..kEEkkkkkEEk...",
        "..kEkEknkEkEk...",
        "..kEEknenkEEk...",
        "..klnnnrnnnlk...",
        "..klmnmnmnmlk...",
        "..klnmnmnmnlk...",
        "..klmnmnmnmlk...",
        "...klnnnnnlk....",
        "....kkrkrkk.....",
        "................",
        "................",
    ],
    "title.early_bird": [  # the rooster on the weathervane
        "................",
        "......pp........",
        ".....kpk........",
        "....kLLkk.......",
        "...ekLkLk.......",
        "....kLLLk...kk..",
        ".....kLLLkkkLk..",
        ".....kLLLLLLLk..",
        "......kLLLLLk...",
        ".......kkkkk....",
        ".........k......",
        "..kkkkkkkkkkkkk.",
        ".........k......",
        ".........k......",
        "........kLk.....",
        "................",
    ],
    "title.weekend": [  # a teacup, steaming
        "................",
        ".....m..m.......",
        "......m..m......",
        ".....m..m.......",
        "................",
        "..kkkkkkkkkk....",
        "..kccccccccCkkk.",
        "..kcvccvccvCk.k.",
        "..kcccccccCCkkk.",
        "...kcccccCCk....",
        "....kccCCCk.....",
        "..kkkkkkkkkkk...",
        "..kCCCCCCCCCk...",
        "...kkkkkkkkk....",
        "................",
        "................",
    ],
    "title.genre_guardian": [  # a gargoyle's face, carved
        "................",
        "..k.........k...",
        "..kLk.....kLk...",
        "..kLLkkkkkLlk...",
        "..kLLLLLLLLlk...",
        ".kLkkLLLLkklLk..",
        ".kLkeLLLLkelLk..",
        ".kLLLLkkLLLllk..",
        "..kLLkLLkLLlk...",
        "..kLkCkkCkLlk...",
        "..kLLkkkkLLlk...",
        "...kLLLLLLlk....",
        "..kLLLLLLLLlk...",
        ".kkkkkkkkkkkkk..",
        "................",
        "................",
    ],
    "title.broken_record": [  # a cracked record
        "................",
        ".....kkkkkk.....",
        "...kknnnnnnkk...",
        "..knnlnnnnknnk..",
        "..knlnnnnkknnk..",
        ".knlnnkkk.knnnk.",
        ".knnnkeek.kknnk.",
        ".knnnker..keknk.",
        ".knnnkee.keeknk.",
        ".knnnnkk.kknnnk.",
        "..knnnnn.knnlk..",
        "..knnnnnk.nlnk..",
        "...kknnnk.nkk...",
        ".....kkkk.kk....",
        "................",
        "................",
    ],
    "title.marathon": [  # an hourglass
        "..kkkkkkkkkkk...",
        "..krrrrrrrrrk...",
        "...kmmmmmmmk....",
        "...kmEEEEEmk....",
        "....kmEEEmk.....",
        ".....kmEmk......",
        "......kek.......",
        ".....kmemk......",
        "....kmmemmk.....",
        "...kmmmemmmk....",
        "...kmmEEEmmk....",
        "...kmEEEEEmk....",
        "..krrrrrrrrrk...",
        "..kkkkkkkkkkk...",
        "................",
        "................",
    ],
    "title.radio_host": [  # the cathedral wireless
        "................",
        ".....kkkkkk.....",
        "...kkrrrrrrkk...",
        "..krrkkkkkkrrk..",
        "..krkeeeeeekrk..",
        ".krkeEEEEEEekrk.",
        ".krkekekekekkrk.",
        ".krkekekekekkrk.",
        ".krkekekekekkrk.",
        ".krkkkkkkkkkkrk.",
        ".krrrrrrrrrrrrk.",
        ".krrkEkrrkEkrrk.",
        ".krrrrrrrrrrrrk.",
        ".kkkkkkkkkkkkkk.",
        "..kk........kk..",
        "................",
    ],
    "title.task_hero": [  # the broom that sweeps by itself
        "............kk..",
        "...........krk..",
        "..........krk...",
        ".........krk....",
        "........krk.....",
        ".......krk......",
        "......kkkk......",
        ".....keEeek.....",
        "....keeEeeek....",
        "...keEeeEeek....",
        "..keeeEeeeek....",
        ".keEeeeeEek.....",
        "keeeeeeeek......",
        "kkekekekk.......",
        "..m...m.........",
        ".m...m..........",
    ],
    "title.grocery_runner": [  # a wicker basket of apples
        "................",
        "....kkkkkkk.....",
        "...kr.....rk....",
        "..kr.......rk...",
        "..kr.kkk.kkrk...",
        "..kkkpppkpppkk..",
        ".kkppcpkpcpppkk.",
        ".krkkpppkppkkrk.",
        ".krrrrrrrrrrrrk.",
        ".krerrerrerrerk.",
        "..krrrrrrrrrrk..",
        "..krerrerrerrk..",
        "...krrrrrrrrk...",
        "....kkkkkkkk....",
        "................",
        "................",
    ],
    "title.planner": [  # the almanac and a quill in its inkwell
        "...........kP...",
        "..........kPPk..",
        ".........kPPk...",
        "........kPPk....",
        ".......kPPk.....",
        "..kkkkkPkkkkk...",
        ".kPPPPkPPPPPPk..",
        ".kPiiikPiiiiPk..",
        ".kPPPPkPPPPPPk..",
        ".kPiiiPPiiiiPk..",
        ".kPPPPPPPPPPPk..",
        ".kPiiPPPkkkkkk..",
        ".kPPPPPPkilLk...",
        ".kkkkkkkkiiik...",
        "........kkkkk...",
        "................",
    ],
    "title.wall_poet": [  # a scroll, unrolled
        "................",
        "..kkkkkkkkkkkk..",
        ".kCPPPPPPPPPPCk.",
        "..kkPPPPPPPPkk..",
        "...kPiiiPiiPk...",
        "...kPPPPPPPPk...",
        "...kPiiPiiiPk...",
        "...kPPPPPPPPk...",
        "...kPiiiiPPPk...",
        "...kPPPPPPPPk...",
        "...kPiiPiiiPk...",
        "..kkPPPPPPPPkk..",
        ".kCPPPPPPPPPPCk.",
        "..kkkkkkkkkkkk..",
        "................",
        "................",
    ],
    "title.courier": [  # a letter sealed with wax
        "................",
        "................",
        ".kkkkkkkkkkkkkk.",
        ".kPkPPPPPPPPkPk.",
        ".kPPkPPPPPPkPPk.",
        ".kPPPkPPPPkPPPk.",
        ".kPPPPkkkkPPPPk.",
        ".kPPPPkpppkPPPk.",
        ".kPPPkpppppkPPk.",
        ".kPPkPppPppPkPk.",
        ".kPkPPkpppkPPkk.",
        ".kkPPPPkkkPPPPk.",
        ".kkkkkkkkkkkkkk.",
        "................",
        "................",
        "................",
    ],
    "title.curator": [  # a gilt frame, a moonlit painting in it
        "................",
        ".kkkkkkkkkkkkkk.",
        ".kEeeeeeeeeeerk.",
        ".kekkkkkkkkkerk.",
        ".kekllllllcCkrk.",
        ".keklllllllCkrk.",
        ".keklllllllllkrk",
        ".keklnnnlllllkrk",
        ".keknnnnnnllnkrk",
        ".keknnnnnnnnnkrk",
        ".kekkkkkkkkkkkrk",
        ".kerrrrrrrrrrrk.",
        ".kkkkkkkkkkkkkk.",
        "................",
        "................",
        "................",
    ],
    "title.high_scorer": [  # a golden goblet
        "................",
        "..kkkkkkkkkkk...",
        ".kEEeeeeeeeerk..",
        ".kEeeeeeeeeerk..",
        ".kkeEeeeeeerkk..",
        "..keEeeeeeerk...",
        "...keeeeeerk....",
        "....keeeerk.....",
        ".....kkekk......",
        "......kek.......",
        "......kek.......",
        ".....kEerk......",
        "...kkeeeerkk....",
        "..kEeeeeeeerk...",
        "..kkkkkkkkkkk...",
        "................",
    ],
    "title.collector": [  # the skeleton key
        "................",
        "...kkkk.........",
        "..keEEek........",
        ".keEkkEek.......",
        ".kek..kek.......",
        ".keEkkeerkkkkkkk",
        "..keeeerreeeeeek",
        "...kkkkkkkkrkrek",
        "...........k.krk",
        ".............kk.",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    "title.game_hopper": [  # two old dice
        "................",
        ".kkkkkkk........",
        ".kcccccCk.......",
        ".kckcccCk.......",
        ".kcccccCk.......",
        ".kccckcCk.......",
        ".kCCCCCCkkkkkk..",
        ".kkkkkkkkcccccCk",
        ".......kckcckcCk",
        ".......kcccccCCk",
        ".......kckcckcCk",
        ".......kcccccCCk",
        ".......kckcckcCk",
        ".......kCCCCCCCk",
        ".......kkkkkkkkk",
        "................",
    ],
    "title.console_hopper": [  # a crystal ball on a claw stand
        "................",
        ".....kkkkkk.....",
        "...kkvvvvvvkk...",
        "..kvcvvvvvvVvk..",
        "..kvvcvvvvVVvk..",
        ".kvvvvvvvVVVVwk.",
        ".kvvvvvVVVVVVwk.",
        ".kvvvVVVVVVVwwk.",
        "..kvVVVVVVVwwk..",
        "..kkVVVVVwwwkk..",
        "...kkkwwwwkkk...",
        "...krkkkkkkrk...",
        "..kreekrrkeerk..",
        "..krrrrrrrrrrk..",
        "..kkkkkkkkkkkk..",
        "................",
    ],
    "title.romhacker": [  # a potion, bubbling
        ".......g........",
        "....g......g....",
        "......kkkk......",
        "......krrk......",
        "......kLLk......",
        ".....kLmmLk.....",
        "....kLmmmmLk....",
        "...kLmmmmmmLk...",
        "..kLggggggggLk..",
        "..kgcgggggggLk..",
        "..kggcggggggLk..",
        "..kgggggggggLk..",
        "..kggggggggLLk..",
        "...kLLLLLLLLk...",
        "....kkkkkkkk....",
        "................",
    ],
}

GLYPHS = {**NOX, **AVATARS, **ROOMS, **MEDALS}

for name, rows in GLYPHS.items():
    assert len(rows) <= 16, (name, len(rows))
    for r in rows:
        assert len(r) == 16, (name, r, len(r))
        assert set(r) <= set(PALETTE) | {"."}, (name, r)


def write():
    data = {"$description": "Legacy: Nox the black cat, moonlit avatars, the manor's room marks and medals. Drawn by hand, pixel by pixel (docs/design/themes/carved-night/pieces.py), MIT.",
            "palette": PALETTE, "glyphs": GLYPHS}
    tmp = OUT.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(data, indent=1, ensure_ascii=False) + "\n")
    os.replace(tmp, OUT)


def preview(path):
    from PIL import Image, ImageDraw
    tokens = json.loads((ROOT / "themes/carved-night/tokens.json").read_text())["color"]["sprite"]
    colour = {k: tokens[v]["$value"] for k, v in PALETTE.items()}
    names = list(GLYPHS)
    cell, cols = 80, 10
    rows_n = (len(names) + cols - 1) // cols
    sheet = Image.new("RGB", (cols * cell, rows_n * cell * 2), "#0a0b1c")
    draw = ImageDraw.Draw(sheet)
    for i, n in enumerate(names):
        for bg_i, bg in enumerate(("#0a0b1c", "#1a1d3c")):
            x0, y0 = (i % cols) * cell, (i // cols) * cell * 2 + bg_i * cell
            draw.rectangle([x0, y0, x0 + cell - 1, y0 + cell - 1], fill=bg)
            for y, row in enumerate(GLYPHS[n]):
                for x, ch in enumerate(row):
                    if ch != ".":
                        draw.rectangle([x0 + 8 + x * 4, y0 + 8 + y * 4, x0 + 11 + x * 4, y0 + 11 + y * 4], fill=colour[ch])
    sheet.save(path)


if __name__ == "__main__":
    write()
    if len(sys.argv) > 1:
        preview(sys.argv[1])
    print("wrote", OUT, len(GLYPHS), "pieces")
